// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/analog-flanger.h"
chdsp* fx_make_analog_flanger(void* mem) { return new (mem) AnalogFlanger(); }
size_t fx_size_analog_flanger() { return sizeof(AnalogFlanger); }
