// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/auto-wah.h"
chdsp* fx_make_auto_wah(void* mem) { return new (mem) AutoWah(); }
size_t fx_size_auto_wah() { return sizeof(AutoWah); }
