// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/barabas-tubescreamer.h"
chdsp* fx_make_barabas_tubescreamer(void* mem) { return new (mem) BarabasTubescreamer(); }
size_t fx_size_barabas_tubescreamer() { return sizeof(BarabasTubescreamer); }
