// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/bbd-chorus.h"
chdsp* fx_make_bbd_chorus(void* mem) { return new (mem) BbdChorus(); }
size_t fx_size_bbd_chorus() { return sizeof(BbdChorus); }
