// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/bbd-drum-delay.h"
chdsp* fx_make_bbd_drum_delay(void* mem) { return new (mem) BbdDrumDelay(); }
size_t fx_size_bbd_drum_delay() { return sizeof(BbdDrumDelay); }
