// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/beat-repeater.h"
chdsp* fx_make_beat_repeater(void* mem) { return new (mem) BeatRepeater(); }
size_t fx_size_beat_repeater() { return sizeof(BeatRepeater); }
