// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/clean-boost.h"
chdsp* fx_make_clean_boost(void* mem) { return new (mem) CleanBoost(); }
size_t fx_size_clean_boost() { return sizeof(CleanBoost); }
