// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/comb-resonator.h"
chdsp* fx_make_comb_resonator(void* mem) { return new (mem) CombResonator(); }
size_t fx_size_comb_resonator() { return sizeof(CombResonator); }
