// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/dattorro-plate.h"
chdsp* fx_make_dattorro_plate(void* mem) { return new (mem) DattorroPlate(); }
size_t fx_size_dattorro_plate() { return sizeof(DattorroPlate); }
