// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/drum-pumping-comp.h"
chdsp* fx_make_drum_pumping_comp(void* mem) { return new (mem) DrumPumpingComp(); }
size_t fx_size_drum_pumping_comp() { return sizeof(DrumPumpingComp); }
