// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/drum-slammer.h"
chdsp* fx_make_drum_slammer(void* mem) { return new (mem) DrumSlammer(); }
size_t fx_size_drum_slammer() { return sizeof(DrumSlammer); }
