// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/dynamic-overdrive.h"
chdsp* fx_make_dynamic_overdrive(void* mem) { return new (mem) DynamicOverdrive(); }
size_t fx_size_dynamic_overdrive() { return sizeof(DynamicOverdrive); }
