// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/ex-chorus-8voice.h"
chdsp* fx_make_ex_chorus_8voice(void* mem) { return new (mem) ExChorus8voice(); }
size_t fx_size_ex_chorus_8voice() { return sizeof(ExChorus8voice); }
