// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/ex-graphic-eq.h"
chdsp* fx_make_ex_graphic_eq(void* mem) { return new (mem) ExGraphicEq(); }
size_t fx_size_ex_graphic_eq() { return sizeof(ExGraphicEq); }
