// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/ex-guitarix-amp.h"
chdsp* fx_make_ex_guitarix_amp(void* mem) { return new (mem) ExGuitarixAmp(); }
size_t fx_size_ex_guitarix_amp() { return sizeof(ExGuitarixAmp); }
