// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/ex-granular-gate.h"
chdsp* fx_make_ex_granular_gate(void* mem) { return new (mem) ExGranularGate(); }
size_t fx_size_ex_granular_gate() { return sizeof(ExGranularGate); }
