// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/ex-harmonic-exciter.h"
chdsp* fx_make_ex_harmonic_exciter(void* mem) { return new (mem) ExHarmonicExciter(); }
size_t fx_size_ex_harmonic_exciter() { return sizeof(ExHarmonicExciter); }
