// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/ex-pitch-feedback-delay.h"
chdsp* fx_make_ex_pitch_feedback_delay(void* mem) { return new (mem) ExPitchFeedbackDelay(); }
size_t fx_size_ex_pitch_feedback_delay() { return sizeof(ExPitchFeedbackDelay); }
