// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/ex-parametric-eq.h"
chdsp* fx_make_ex_parametric_eq(void* mem) { return new (mem) ExParametricEq(); }
size_t fx_size_ex_parametric_eq() { return sizeof(ExParametricEq); }
