// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/ex-tremolo-autopan.h"
chdsp* fx_make_ex_tremolo_autopan(void* mem) { return new (mem) ExTremoloAutopan(); }
size_t fx_size_ex_tremolo_autopan() { return sizeof(ExTremoloAutopan); }
