// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/expander-gate.h"
chdsp* fx_make_expander_gate(void* mem) { return new (mem) ExpanderGate(); }
size_t fx_size_expander_gate() { return sizeof(ExpanderGate); }
