// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/freq-shifter.h"
chdsp* fx_make_freq_shifter(void* mem) { return new (mem) FreqShifter(); }
size_t fx_size_freq_shifter() { return sizeof(FreqShifter); }
