// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gated-snare-reverb.h"
chdsp* fx_make_gated_snare_reverb(void* mem) { return new (mem) GatedSnareReverb(); }
size_t fx_size_gated_snare_reverb() { return sizeof(GatedSnareReverb); }
