// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-autowah.h"
chdsp* fx_make_gx_autowah(void* mem) { return new (mem) GxAutowah(); }
size_t fx_size_gx_autowah() { return sizeof(GxAutowah); }
