// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-aclipper.h"
chdsp* fx_make_gx_aclipper(void* mem) { return new (mem) GxAclipper(); }
size_t fx_size_gx_aclipper() { return sizeof(GxAclipper); }
