// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-astrofuzz.h"
chdsp* fx_make_gx_astrofuzz(void* mem) { return new (mem) GxAstrofuzz(); }
size_t fx_size_gx_astrofuzz() { return sizeof(GxAstrofuzz); }
