// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-axface.h"
chdsp* fx_make_gx_axface(void* mem) { return new (mem) GxAxface(); }
size_t fx_size_gx_axface() { return sizeof(GxAxface); }
