// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-bossds1.h"
chdsp* fx_make_gx_bossds1(void* mem) { return new (mem) GxBossds1(); }
size_t fx_size_gx_bossds1() { return sizeof(GxBossds1); }
