// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-bmp.h"
chdsp* fx_make_gx_bmp(void* mem) { return new (mem) GxBmp(); }
size_t fx_size_gx_bmp() { return sizeof(GxBmp); }
