// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-bassbooster.h"
chdsp* fx_make_gx_bassbooster(void* mem) { return new (mem) GxBassbooster(); }
size_t fx_size_gx_bassbooster() { return sizeof(GxBassbooster); }
