// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-bassboom.h"
chdsp* fx_make_gx_bassboom(void* mem) { return new (mem) GxBassboom(); }
size_t fx_size_gx_bassboom() { return sizeof(GxBassboom); }
