// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-bfuzz.h"
chdsp* fx_make_gx_bfuzz(void* mem) { return new (mem) GxBfuzz(); }
size_t fx_size_gx_bfuzz() { return sizeof(GxBfuzz); }
