// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-buzz.h"
chdsp* fx_make_gx_buzz(void* mem) { return new (mem) GxBuzz(); }
size_t fx_size_gx_buzz() { return sizeof(GxBuzz); }
