// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-bigmuff.h"
chdsp* fx_make_gx_bigmuff(void* mem) { return new (mem) GxBigmuff(); }
size_t fx_size_gx_bigmuff() { return sizeof(GxBigmuff); }
