// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-crybaby.h"
chdsp* fx_make_gx_crybaby(void* mem) { return new (mem) GxCrybaby(); }
size_t fx_size_gx_crybaby() { return sizeof(GxCrybaby); }
