// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-cstb.h"
chdsp* fx_make_gx_cstb(void* mem) { return new (mem) GxCstb(); }
size_t fx_size_gx_cstb() { return sizeof(GxCstb); }
