// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-chorus-mono.h"
chdsp* fx_make_gx_chorus_mono(void* mem) { return new (mem) GxChorusMono(); }
size_t fx_size_gx_chorus_mono() { return sizeof(GxChorusMono); }
