// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-chorus.h"
chdsp* fx_make_gx_chorus(void* mem) { return new (mem) GxChorus(); }
size_t fx_size_gx_chorus() { return sizeof(GxChorus); }
