// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-colwah.h"
chdsp* fx_make_gx_colwah(void* mem) { return new (mem) GxColwah(); }
size_t fx_size_gx_colwah() { return sizeof(GxColwah); }
