// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-compressor.h"
chdsp* fx_make_gx_compressor(void* mem) { return new (mem) GxCompressor(); }
size_t fx_size_gx_compressor() { return sizeof(GxCompressor); }
