// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-coverd.h"
chdsp* fx_make_gx_coverd(void* mem) { return new (mem) GxCoverd(); }
size_t fx_size_gx_coverd() { return sizeof(GxCoverd); }
