// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-dunwah.h"
chdsp* fx_make_gx_dunwah(void* mem) { return new (mem) GxDunwah(); }
size_t fx_size_gx_dunwah() { return sizeof(GxDunwah); }
