// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-delay.h"
chdsp* fx_make_gx_delay(void* mem) { return new (mem) GxDelay(); }
size_t fx_size_gx_delay() { return sizeof(GxDelay); }
