// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-echo.h"
chdsp* fx_make_gx_echo(void* mem) { return new (mem) GxEcho(); }
size_t fx_size_gx_echo() { return sizeof(GxEcho); }
