// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-eldist.h"
chdsp* fx_make_gx_eldist(void* mem) { return new (mem) GxEldist(); }
size_t fx_size_gx_eldist() { return sizeof(GxEldist); }
