// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-eq.h"
chdsp* fx_make_gx_eq(void* mem) { return new (mem) GxEq(); }
size_t fx_size_gx_eq() { return sizeof(GxEq); }
