// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-expander.h"
chdsp* fx_make_gx_expander(void* mem) { return new (mem) GxExpander(); }
size_t fx_size_gx_expander() { return sizeof(GxExpander); }
