// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-fuzzface.h"
chdsp* fx_make_gx_fuzzface(void* mem) { return new (mem) GxFuzzface(); }
size_t fx_size_gx_fuzzface() { return sizeof(GxFuzzface); }
