// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-fumaster.h"
chdsp* fx_make_gx_fumaster(void* mem) { return new (mem) GxFumaster(); }
size_t fx_size_gx_fumaster() { return sizeof(GxFumaster); }
