// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-fuzzfacefm.h"
chdsp* fx_make_gx_fuzzfacefm(void* mem) { return new (mem) GxFuzzfacefm(); }
size_t fx_size_gx_fuzzfacefm() { return sizeof(GxFuzzfacefm); }
