// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-fuzzfacerm.h"
chdsp* fx_make_gx_fuzzfacerm(void* mem) { return new (mem) GxFuzzfacerm(); }
size_t fx_size_gx_fuzzfacerm() { return sizeof(GxFuzzfacerm); }
