// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-flanger-mono.h"
chdsp* fx_make_gx_flanger_mono(void* mem) { return new (mem) GxFlangerMono(); }
size_t fx_size_gx_flanger_mono() { return sizeof(GxFlangerMono); }
