// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-flanger.h"
chdsp* fx_make_gx_flanger(void* mem) { return new (mem) GxFlanger(); }
size_t fx_size_gx_flanger() { return sizeof(GxFlanger); }
