// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-foxwah.h"
chdsp* fx_make_gx_foxwah(void* mem) { return new (mem) GxFoxwah(); }
size_t fx_size_gx_foxwah() { return sizeof(GxFoxwah); }
