// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-foxeylady.h"
chdsp* fx_make_gx_foxeylady(void* mem) { return new (mem) GxFoxeylady(); }
size_t fx_size_gx_foxeylady() { return sizeof(GxFoxeylady); }
