// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-freeverb.h"
chdsp* fx_make_gx_freeverb(void* mem) { return new (mem) GxFreeverb(); }
size_t fx_size_gx_freeverb() { return sizeof(GxFreeverb); }
