// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gx-chump.h"
chdsp* fx_make_gx_gx_chump(void* mem) { return new (mem) GxGxChump(); }
size_t fx_size_gx_gx_chump() { return sizeof(GxGxChump); }
