// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp11.h"
chdsp* fx_make_gx_gxamp11(void* mem) { return new (mem) GxGxamp11(); }
size_t fx_size_gx_gxamp11() { return sizeof(GxGxamp11); }
