// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp16.h"
chdsp* fx_make_gx_gxamp16(void* mem) { return new (mem) GxGxamp16(); }
size_t fx_size_gx_gxamp16() { return sizeof(GxGxamp16); }
