// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-graphiceq.h"
chdsp* fx_make_gx_graphiceq(void* mem) { return new (mem) GxGraphiceq(); }
size_t fx_size_gx_graphiceq() { return sizeof(GxGraphiceq); }
