// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxtubevibrato.h"
chdsp* fx_make_gx_gxtubevibrato(void* mem) { return new (mem) GxGxtubevibrato(); }
size_t fx_size_gx_gxtubevibrato() { return sizeof(GxGxtubevibrato); }
