// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp9.h"
chdsp* fx_make_gx_gxamp9(void* mem) { return new (mem) GxGxamp9(); }
size_t fx_size_gx_gxamp9() { return sizeof(GxGxamp9); }
