// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxmetal-amp.h"
chdsp* fx_make_gx_gxmetal_amp(void* mem) { return new (mem) GxGxmetalAmp(); }
size_t fx_size_gx_gxmetal_amp() { return sizeof(GxGxmetalAmp); }
