// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gcb-95.h"
chdsp* fx_make_gx_gcb_95(void* mem) { return new (mem) GxGcb95(); }
size_t fx_size_gx_gcb_95() { return sizeof(GxGcb95); }
