// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp4.h"
chdsp* fx_make_gx_gxamp4(void* mem) { return new (mem) GxGxamp4(); }
size_t fx_size_gx_gxamp4() { return sizeof(GxGxamp4); }
