// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp.h"
chdsp* fx_make_gx_gxamp(void* mem) { return new (mem) GxGxamp(); }
size_t fx_size_gx_gxamp() { return sizeof(GxGxamp); }
