// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxechocat.h"
chdsp* fx_make_gx_gxechocat(void* mem) { return new (mem) GxGxechocat(); }
size_t fx_size_gx_gxechocat() { return sizeof(GxGxechocat); }
