// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp3.h"
chdsp* fx_make_gx_gxamp3(void* mem) { return new (mem) GxGxamp3(); }
size_t fx_size_gx_gxamp3() { return sizeof(GxGxamp3); }
