// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxtilttone.h"
chdsp* fx_make_gx_gxtilttone(void* mem) { return new (mem) GxGxtilttone(); }
size_t fx_size_gx_gxtilttone() { return sizeof(GxGxtilttone); }
