// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp2.h"
chdsp* fx_make_gx_gxamp2(void* mem) { return new (mem) GxGxamp2(); }
size_t fx_size_gx_gxamp2() { return sizeof(GxGxamp2); }
