// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gx-studiopre.h"
chdsp* fx_make_gx_gx_studiopre(void* mem) { return new (mem) GxGxStudiopre(); }
size_t fx_size_gx_gx_studiopre() { return sizeof(GxGxStudiopre); }
