// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxtubedelay.h"
chdsp* fx_make_gx_gxtubedelay(void* mem) { return new (mem) GxGxtubedelay(); }
size_t fx_size_gx_gxtubedelay() { return sizeof(GxGxtubedelay); }
