// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gx-bigchump.h"
chdsp* fx_make_gx_gx_bigchump(void* mem) { return new (mem) GxGxBigchump(); }
size_t fx_size_gx_gx_bigchump() { return sizeof(GxGxBigchump); }
