// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp18.h"
chdsp* fx_make_gx_gxamp18(void* mem) { return new (mem) GxGxamp18(); }
size_t fx_size_gx_gxamp18() { return sizeof(GxGxamp18); }
