// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp10.h"
chdsp* fx_make_gx_gxamp10(void* mem) { return new (mem) GxGxamp10(); }
size_t fx_size_gx_gxamp10() { return sizeof(GxGxamp10); }
