// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gx-distortion.h"
chdsp* fx_make_gx_gx_distortion(void* mem) { return new (mem) GxGxDistortion(); }
size_t fx_size_gx_gx_distortion() { return sizeof(GxGxDistortion); }
