// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp15.h"
chdsp* fx_make_gx_gxamp15(void* mem) { return new (mem) GxGxamp15(); }
size_t fx_size_gx_gxamp15() { return sizeof(GxGxamp15); }
