// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp12.h"
chdsp* fx_make_gx_gxamp12(void* mem) { return new (mem) GxGxamp12(); }
size_t fx_size_gx_gxamp12() { return sizeof(GxGxamp12); }
