// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gx-vibrochump.h"
chdsp* fx_make_gx_gx_vibrochump(void* mem) { return new (mem) GxGxVibrochump(); }
size_t fx_size_gx_gx_vibrochump() { return sizeof(GxGxVibrochump); }
