// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp8.h"
chdsp* fx_make_gx_gxamp8(void* mem) { return new (mem) GxGxamp8(); }
size_t fx_size_gx_gxamp8() { return sizeof(GxGxamp8); }
