// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp17.h"
chdsp* fx_make_gx_gxamp17(void* mem) { return new (mem) GxGxamp17(); }
size_t fx_size_gx_gxamp17() { return sizeof(GxGxamp17); }
