// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp13.h"
chdsp* fx_make_gx_gxamp13(void* mem) { return new (mem) GxGxamp13(); }
size_t fx_size_gx_gxamp13() { return sizeof(GxGxamp13); }
