// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gxamp14.h"
chdsp* fx_make_gx_gxamp14(void* mem) { return new (mem) GxGxamp14(); }
size_t fx_size_gx_gxamp14() { return sizeof(GxGxamp14); }
