// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-gx-w20.h"
chdsp* fx_make_gx_gx_w20(void* mem) { return new (mem) GxGxW20(); }
size_t fx_size_gx_gx_w20() { return sizeof(GxGxW20); }
