// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-hfb.h"
chdsp* fx_make_gx_hfb(void* mem) { return new (mem) GxHfb(); }
size_t fx_size_gx_hfb() { return sizeof(GxHfb); }
