// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-hornet.h"
chdsp* fx_make_gx_hornet(void* mem) { return new (mem) GxHornet(); }
size_t fx_size_gx_hornet() { return sizeof(GxHornet); }
