// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-hogsfoot.h"
chdsp* fx_make_gx_hogsfoot(void* mem) { return new (mem) GxHogsfoot(); }
size_t fx_size_gx_hogsfoot() { return sizeof(GxHogsfoot); }
