// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-highbooster.h"
chdsp* fx_make_gx_highbooster(void* mem) { return new (mem) GxHighbooster(); }
size_t fx_size_gx_highbooster() { return sizeof(GxHighbooster); }
