// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-jenwah.h"
chdsp* fx_make_gx_jenwah(void* mem) { return new (mem) GxJenwah(); }
size_t fx_size_gx_jenwah() { return sizeof(GxJenwah); }
