// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-lpbboost.h"
chdsp* fx_make_gx_lpbboost(void* mem) { return new (mem) GxLpbboost(); }
size_t fx_size_gx_lpbboost() { return sizeof(GxLpbboost); }
