// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-low-high-pass.h"
chdsp* fx_make_gx_low_high_pass(void* mem) { return new (mem) GxLowHighPass(); }
size_t fx_size_gx_low_high_pass() { return sizeof(GxLowHighPass); }
