// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-mole.h"
chdsp* fx_make_gx_mole(void* mem) { return new (mem) GxMole(); }
size_t fx_size_gx_mole() { return sizeof(GxMole); }
