// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-mbreverb.h"
chdsp* fx_make_gx_mbreverb(void* mem) { return new (mem) GxMbreverb(); }
size_t fx_size_gx_mbreverb() { return sizeof(GxMbreverb); }
