// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-moog.h"
chdsp* fx_make_gx_moog(void* mem) { return new (mem) GxMoog(); }
size_t fx_size_gx_moog() { return sizeof(GxMoog); }
