// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-mbclipper.h"
chdsp* fx_make_gx_mbclipper(void* mem) { return new (mem) GxMbclipper(); }
size_t fx_size_gx_mbclipper() { return sizeof(GxMbclipper); }
