// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-mbchor.h"
chdsp* fx_make_gx_mbchor(void* mem) { return new (mem) GxMbchor(); }
size_t fx_size_gx_mbchor() { return sizeof(GxMbchor); }
