// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-mbc.h"
chdsp* fx_make_gx_mbc(void* mem) { return new (mem) GxMbc(); }
size_t fx_size_gx_mbc() { return sizeof(GxMbc); }
