// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-mxrdist.h"
chdsp* fx_make_gx_mxrdist(void* mem) { return new (mem) GxMxrdist(); }
size_t fx_size_gx_mxrdist() { return sizeof(GxMxrdist); }
