// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-maestrowah.h"
chdsp* fx_make_gx_maestrowah(void* mem) { return new (mem) GxMaestrowah(); }
size_t fx_size_gx_maestrowah() { return sizeof(GxMaestrowah); }
