// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-muff.h"
chdsp* fx_make_gx_muff(void* mem) { return new (mem) GxMuff(); }
size_t fx_size_gx_muff() { return sizeof(GxMuff); }
