// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-mbd.h"
chdsp* fx_make_gx_mbd(void* mem) { return new (mem) GxMbd(); }
size_t fx_size_gx_mbd() { return sizeof(GxMbd); }
