// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-mbdel.h"
chdsp* fx_make_gx_mbdel(void* mem) { return new (mem) GxMbdel(); }
size_t fx_size_gx_mbdel() { return sizeof(GxMbdel); }
