// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-mbe.h"
chdsp* fx_make_gx_mbe(void* mem) { return new (mem) GxMbe(); }
size_t fx_size_gx_mbe() { return sizeof(GxMbe); }
