// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-mbcs.h"
chdsp* fx_make_gx_mbcs(void* mem) { return new (mem) GxMbcs(); }
size_t fx_size_gx_mbcs() { return sizeof(GxMbcs); }
