// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-overdrive.h"
chdsp* fx_make_gx_overdrive(void* mem) { return new (mem) GxOverdrive(); }
size_t fx_size_gx_overdrive() { return sizeof(GxOverdrive); }
