// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-phaser-mono.h"
chdsp* fx_make_gx_phaser_mono(void* mem) { return new (mem) GxPhaserMono(); }
size_t fx_size_gx_phaser_mono() { return sizeof(GxPhaserMono); }
