// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-phaser.h"
chdsp* fx_make_gx_phaser(void* mem) { return new (mem) GxPhaser(); }
size_t fx_size_gx_phaser() { return sizeof(GxPhaser); }
