// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-preamp.h"
chdsp* fx_make_gx_preamp(void* mem) { return new (mem) GxPreamp(); }
size_t fx_size_gx_preamp() { return sizeof(GxPreamp); }
