// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-rangem.h"
chdsp* fx_make_gx_rangem(void* mem) { return new (mem) GxRangem(); }
size_t fx_size_gx_rangem() { return sizeof(GxRangem); }
