// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-reso-tube.h"
chdsp* fx_make_gx_reso_tube(void* mem) { return new (mem) GxResoTube(); }
size_t fx_size_gx_reso_tube() { return sizeof(GxResoTube); }
