// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-rolandwah.h"
chdsp* fx_make_gx_rolandwah(void* mem) { return new (mem) GxRolandwah(); }
size_t fx_size_gx_rolandwah() { return sizeof(GxRolandwah); }
