// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-selwah.h"
chdsp* fx_make_gx_selwah(void* mem) { return new (mem) GxSelwah(); }
size_t fx_size_gx_selwah() { return sizeof(GxSelwah); }
