// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-stereodelay.h"
chdsp* fx_make_gx_stereodelay(void* mem) { return new (mem) GxStereodelay(); }
size_t fx_size_gx_stereodelay() { return sizeof(GxStereodelay); }
