// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-softclip.h"
chdsp* fx_make_gx_softclip(void* mem) { return new (mem) GxSoftclip(); }
size_t fx_size_gx_softclip() { return sizeof(GxSoftclip); }
