// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-stereoecho.h"
chdsp* fx_make_gx_stereoecho(void* mem) { return new (mem) GxStereoecho(); }
size_t fx_size_gx_stereoecho() { return sizeof(GxStereoecho); }
