// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-selecteq.h"
chdsp* fx_make_gx_selecteq(void* mem) { return new (mem) GxSelecteq(); }
size_t fx_size_gx_selecteq() { return sizeof(GxSelecteq); }
