// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-susta.h"
chdsp* fx_make_gx_susta(void* mem) { return new (mem) GxSusta(); }
size_t fx_size_gx_susta() { return sizeof(GxSusta); }
