// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-scream.h"
chdsp* fx_make_gx_scream(void* mem) { return new (mem) GxScream(); }
size_t fx_size_gx_scream() { return sizeof(GxScream); }
