// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-jcm2000.h"
chdsp* fx_make_gx_tonestack_jcm2000(void* mem) { return new (mem) GxTonestackJcm2000(); }
size_t fx_size_gx_tonestack_jcm2000() { return sizeof(GxTonestackJcm2000); }
