// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-roland.h"
chdsp* fx_make_gx_tonestack_roland(void* mem) { return new (mem) GxTonestackRoland(); }
size_t fx_size_gx_tonestack_roland() { return sizeof(GxTonestackRoland); }
