// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-sovtek.h"
chdsp* fx_make_gx_tonestack_sovtek(void* mem) { return new (mem) GxTonestackSovtek(); }
size_t fx_size_gx_tonestack_sovtek() { return sizeof(GxTonestackSovtek); }
