// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tube.h"
chdsp* fx_make_gx_tube(void* mem) { return new (mem) GxTube(); }
size_t fx_size_gx_tube() { return sizeof(GxTube); }
