// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-bm.h"
chdsp* fx_make_gx_tonestack_bm(void* mem) { return new (mem) GxTonestackBm(); }
size_t fx_size_gx_tonestack_bm() { return sizeof(GxTonestackBm); }
