// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-ampeg.h"
chdsp* fx_make_gx_tonestack_ampeg(void* mem) { return new (mem) GxTonestackAmpeg(); }
size_t fx_size_gx_tonestack_ampeg() { return sizeof(GxTonestackAmpeg); }
