// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tremolo.h"
chdsp* fx_make_gx_tremolo(void* mem) { return new (mem) GxTremolo(); }
size_t fx_size_gx_tremolo() { return sizeof(GxTremolo); }
