// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tone.h"
chdsp* fx_make_gx_tone(void* mem) { return new (mem) GxTone(); }
size_t fx_size_gx_tone() { return sizeof(GxTone); }
