// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-ampeg-rev.h"
chdsp* fx_make_gx_tonestack_ampeg_rev(void* mem) { return new (mem) GxTonestackAmpegRev(); }
size_t fx_size_gx_tonestack_ampeg_rev() { return sizeof(GxTonestackAmpegRev); }
