// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-fender-deville.h"
chdsp* fx_make_gx_tonestack_fender_deville(void* mem) { return new (mem) GxTonestackFenderDeville(); }
size_t fx_size_gx_tonestack_fender_deville() { return sizeof(GxTonestackFenderDeville); }
