// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-crunch.h"
chdsp* fx_make_gx_tonestack_crunch(void* mem) { return new (mem) GxTonestackCrunch(); }
size_t fx_size_gx_tonestack_crunch() { return sizeof(GxTonestackCrunch); }
