// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-soldano.h"
chdsp* fx_make_gx_tonestack_soldano(void* mem) { return new (mem) GxTonestackSoldano(); }
size_t fx_size_gx_tonestack_soldano() { return sizeof(GxTonestackSoldano); }
