// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-m2199.h"
chdsp* fx_make_gx_tonestack_m2199(void* mem) { return new (mem) GxTonestackM2199(); }
size_t fx_size_gx_tonestack_m2199() { return sizeof(GxTonestackM2199); }
