// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-twin.h"
chdsp* fx_make_gx_tonestack_twin(void* mem) { return new (mem) GxTonestackTwin(); }
size_t fx_size_gx_tonestack_twin() { return sizeof(GxTonestackTwin); }
