// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-jcm800.h"
chdsp* fx_make_gx_tonestack_jcm800(void* mem) { return new (mem) GxTonestackJcm800(); }
size_t fx_size_gx_tonestack_jcm800() { return sizeof(GxTonestackJcm800); }
