// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonecontroll.h"
chdsp* fx_make_gx_tonecontroll(void* mem) { return new (mem) GxTonecontroll(); }
size_t fx_size_gx_tonecontroll() { return sizeof(GxTonecontroll); }
