// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-fender-blues.h"
chdsp* fx_make_gx_tonestack_fender_blues(void* mem) { return new (mem) GxTonestackFenderBlues(); }
size_t fx_size_gx_tonestack_fender_blues() { return sizeof(GxTonestackFenderBlues); }
