// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-peavey.h"
chdsp* fx_make_gx_tonestack_peavey(void* mem) { return new (mem) GxTonestackPeavey(); }
size_t fx_size_gx_tonestack_peavey() { return sizeof(GxTonestackPeavey); }
