// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-bassman.h"
chdsp* fx_make_gx_tonestack_bassman(void* mem) { return new (mem) GxTonestackBassman(); }
size_t fx_size_gx_tonestack_bassman() { return sizeof(GxTonestackBassman); }
