// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-princeton.h"
chdsp* fx_make_gx_tonestack_princeton(void* mem) { return new (mem) GxTonestackPrinceton(); }
size_t fx_size_gx_tonestack_princeton() { return sizeof(GxTonestackPrinceton); }
