// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-jtm45.h"
chdsp* fx_make_gx_tonestack_jtm45(void* mem) { return new (mem) GxTonestackJtm45(); }
size_t fx_size_gx_tonestack_jtm45() { return sizeof(GxTonestackJtm45); }
