// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tube3.h"
chdsp* fx_make_gx_tube3(void* mem) { return new (mem) GxTube3(); }
size_t fx_size_gx_tube3() { return sizeof(GxTube3); }
