// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-ac30.h"
chdsp* fx_make_gx_tonestack_ac30(void* mem) { return new (mem) GxTonestackAc30(); }
size_t fx_size_gx_tonestack_ac30() { return sizeof(GxTonestackAc30); }
