// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-ts9sim.h"
chdsp* fx_make_gx_ts9sim(void* mem) { return new (mem) GxTs9sim(); }
size_t fx_size_gx_ts9sim() { return sizeof(GxTs9sim); }
