// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-groove.h"
chdsp* fx_make_gx_tonestack_groove(void* mem) { return new (mem) GxTonestackGroove(); }
size_t fx_size_gx_tonestack_groove() { return sizeof(GxTonestackGroove); }
