// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-engl.h"
chdsp* fx_make_gx_tonestack_engl(void* mem) { return new (mem) GxTonestackEngl(); }
size_t fx_size_gx_tonestack_engl() { return sizeof(GxTonestackEngl); }
