// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-tonestack-ibanez.h"
chdsp* fx_make_gx_tonestack_ibanez(void* mem) { return new (mem) GxTonestackIbanez(); }
size_t fx_size_gx_tonestack_ibanez() { return sizeof(GxTonestackIbanez); }
