// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-voxwah.h"
chdsp* fx_make_gx_voxwah(void* mem) { return new (mem) GxVoxwah(); }
size_t fx_size_gx_voxwah() { return sizeof(GxVoxwah); }
