// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/gx-zita-rev1.h"
chdsp* fx_make_gx_zita_rev1(void* mem) { return new (mem) GxZitaRev1(); }
size_t fx_size_gx_zita_rev1() { return sizeof(GxZitaRev1); }
