// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/harmonic-tremolo.h"
chdsp* fx_make_harmonic_tremolo(void* mem) { return new (mem) HarmonicTremolo(); }
size_t fx_size_harmonic_tremolo() { return sizeof(HarmonicTremolo); }
