// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/infinite-compressor.h"
chdsp* fx_make_infinite_compressor(void* mem) { return new (mem) InfiniteCompressor(); }
size_t fx_size_infinite_compressor() { return sizeof(InfiniteCompressor); }
