// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/klon-centaur.h"
chdsp* fx_make_klon_centaur(void* mem) { return new (mem) KlonCentaur(); }
size_t fx_size_klon_centaur() { return sizeof(KlonCentaur); }
