// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/kpp-single2humbucker.h"
chdsp* fx_make_kpp_single2humbucker(void* mem) { return new (mem) KppSingle2humbucker(); }
size_t fx_size_kpp_single2humbucker() { return sizeof(KppSingle2humbucker); }
