// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/kpp-distruction.h"
chdsp* fx_make_kpp_distruction(void* mem) { return new (mem) KppDistruction(); }
size_t fx_size_kpp_distruction() { return sizeof(KppDistruction); }
