// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/kpp-octaver.h"
chdsp* fx_make_kpp_octaver(void* mem) { return new (mem) KppOctaver(); }
size_t fx_size_kpp_octaver() { return sizeof(KppOctaver); }
