// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/kpp-deadgate.h"
chdsp* fx_make_kpp_deadgate(void* mem) { return new (mem) KppDeadgate(); }
size_t fx_size_kpp_deadgate() { return sizeof(KppDeadgate); }
