// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/kpp-fuzz.h"
chdsp* fx_make_kpp_fuzz(void* mem) { return new (mem) KppFuzz(); }
size_t fx_size_kpp_fuzz() { return sizeof(KppFuzz); }
