// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/kpp-bluedream.h"
chdsp* fx_make_kpp_bluedream(void* mem) { return new (mem) KppBluedream(); }
size_t fx_size_kpp_bluedream() { return sizeof(KppBluedream); }
