// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-tape-hysteresis.h"
chdsp* fx_make_lib_tape_hysteresis(void* mem) { return new (mem) LibTapeHysteresis(); }
size_t fx_size_lib_tape_hysteresis() { return sizeof(LibTapeHysteresis); }
