// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-ring-mod.h"
chdsp* fx_make_lib_ring_mod(void* mem) { return new (mem) LibRingMod(); }
size_t fx_size_lib_ring_mod() { return sizeof(LibRingMod); }
