// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-zita-rev1.h"
chdsp* fx_make_lib_zita_rev1(void* mem) { return new (mem) LibZitaRev1(); }
size_t fx_size_lib_zita_rev1() { return sizeof(LibZitaRev1); }
