// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-fb-compressor.h"
chdsp* fx_make_lib_fb_compressor(void* mem) { return new (mem) LibFbCompressor(); }
size_t fx_size_lib_fb_compressor() { return sizeof(LibFbCompressor); }
