// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-rms-peak-limiter.h"
chdsp* fx_make_lib_rms_peak_limiter(void* mem) { return new (mem) LibRmsPeakLimiter(); }
size_t fx_size_lib_rms_peak_limiter() { return sizeof(LibRmsPeakLimiter); }
