// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-lookahead-limiter.h"
chdsp* fx_make_lib_lookahead_limiter(void* mem) { return new (mem) LibLookaheadLimiter(); }
size_t fx_size_lib_lookahead_limiter() { return sizeof(LibLookaheadLimiter); }
