// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-jcrev.h"
chdsp* fx_make_lib_jcrev(void* mem) { return new (mem) LibJcrev(); }
size_t fx_size_lib_jcrev() { return sizeof(LibJcrev); }
