// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-pitch-shift.h"
chdsp* fx_make_lib_pitch_shift(void* mem) { return new (mem) LibPitchShift(); }
size_t fx_size_lib_pitch_shift() { return sizeof(LibPitchShift); }
