// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-cubicnl.h"
chdsp* fx_make_lib_cubicnl(void* mem) { return new (mem) LibCubicnl(); }
size_t fx_size_lib_cubicnl() { return sizeof(LibCubicnl); }
