// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-wavefolder.h"
chdsp* fx_make_lib_wavefolder(void* mem) { return new (mem) LibWavefolder(); }
size_t fx_size_lib_wavefolder() { return sizeof(LibWavefolder); }
