// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-sallenkey-lpf.h"
chdsp* fx_make_lib_sallenkey_lpf(void* mem) { return new (mem) LibSallenkeyLpf(); }
size_t fx_size_lib_sallenkey_lpf() { return sizeof(LibSallenkeyLpf); }
