// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-moog-vcf.h"
chdsp* fx_make_lib_moog_vcf(void* mem) { return new (mem) LibMoogVcf(); }
size_t fx_size_lib_moog_vcf() { return sizeof(LibMoogVcf); }
