// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-moog-half-ladder.h"
chdsp* fx_make_lib_moog_half_ladder(void* mem) { return new (mem) LibMoogHalfLadder(); }
size_t fx_size_lib_moog_half_ladder() { return sizeof(LibMoogHalfLadder); }
