// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-adaa-drive.h"
chdsp* fx_make_lib_adaa_drive(void* mem) { return new (mem) LibAdaaDrive(); }
size_t fx_size_lib_adaa_drive() { return sizeof(LibAdaaDrive); }
