// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-greyhole.h"
chdsp* fx_make_lib_greyhole(void* mem) { return new (mem) LibGreyhole(); }
size_t fx_size_lib_greyhole() { return sizeof(LibGreyhole); }
