// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-speaker-sim.h"
chdsp* fx_make_lib_speaker_sim(void* mem) { return new (mem) LibSpeakerSim(); }
size_t fx_size_lib_speaker_sim() { return sizeof(LibSpeakerSim); }
