// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-reverse-echo.h"
chdsp* fx_make_lib_reverse_echo(void* mem) { return new (mem) LibReverseEcho(); }
size_t fx_size_lib_reverse_echo() { return sizeof(LibReverseEcho); }
