// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-flanger.h"
chdsp* fx_make_lib_flanger(void* mem) { return new (mem) LibFlanger(); }
size_t fx_size_lib_flanger() { return sizeof(LibFlanger); }
