// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-oberheim-bpf.h"
chdsp* fx_make_lib_oberheim_bpf(void* mem) { return new (mem) LibOberheimBpf(); }
size_t fx_size_lib_oberheim_bpf() { return sizeof(LibOberheimBpf); }
