// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-jpverb.h"
chdsp* fx_make_lib_jpverb(void* mem) { return new (mem) LibJpverb(); }
size_t fx_size_lib_jpverb() { return sizeof(LibJpverb); }
