// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-freeverb.h"
chdsp* fx_make_lib_freeverb(void* mem) { return new (mem) LibFreeverb(); }
size_t fx_size_lib_freeverb() { return sizeof(LibFreeverb); }
