// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-gate.h"
chdsp* fx_make_lib_gate(void* mem) { return new (mem) LibGate(); }
size_t fx_size_lib_gate() { return sizeof(LibGate); }
