// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-jos-compressor.h"
chdsp* fx_make_lib_jos_compressor(void* mem) { return new (mem) LibJosCompressor(); }
size_t fx_size_lib_jos_compressor() { return sizeof(LibJosCompressor); }
