// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-expander.h"
chdsp* fx_make_lib_expander(void* mem) { return new (mem) LibExpander(); }
size_t fx_size_lib_expander() { return sizeof(LibExpander); }
