// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-dattorro.h"
chdsp* fx_make_lib_dattorro(void* mem) { return new (mem) LibDattorro(); }
size_t fx_size_lib_dattorro() { return sizeof(LibDattorro); }
