// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-harmonizer.h"
chdsp* fx_make_lib_harmonizer(void* mem) { return new (mem) LibHarmonizer(); }
size_t fx_size_lib_harmonizer() { return sizeof(LibHarmonizer); }
