// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-phaser2-8.h"
chdsp* fx_make_lib_phaser2_8(void* mem) { return new (mem) LibPhaser28(); }
size_t fx_size_lib_phaser2_8() { return sizeof(LibPhaser28); }
