// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-ff-compressor.h"
chdsp* fx_make_lib_ff_compressor(void* mem) { return new (mem) LibFfCompressor(); }
size_t fx_size_lib_ff_compressor() { return sizeof(LibFfCompressor); }
