// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-diode-ladder.h"
chdsp* fx_make_lib_diode_ladder(void* mem) { return new (mem) LibDiodeLadder(); }
size_t fx_size_lib_diode_ladder() { return sizeof(LibDiodeLadder); }
