// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-springreverb.h"
chdsp* fx_make_lib_springreverb(void* mem) { return new (mem) LibSpringreverb(); }
size_t fx_size_lib_springreverb() { return sizeof(LibSpringreverb); }
