// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-wah4.h"
chdsp* fx_make_lib_wah4(void* mem) { return new (mem) LibWah4(); }
size_t fx_size_lib_wah4() { return sizeof(LibWah4); }
