// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-korg35-hpf.h"
chdsp* fx_make_lib_korg35_hpf(void* mem) { return new (mem) LibKorg35Hpf(); }
size_t fx_size_lib_korg35_hpf() { return sizeof(LibKorg35Hpf); }
