// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-oberheim-lpf.h"
chdsp* fx_make_lib_oberheim_lpf(void* mem) { return new (mem) LibOberheimLpf(); }
size_t fx_size_lib_oberheim_lpf() { return sizeof(LibOberheimLpf); }
