// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-oberheim-hpf.h"
chdsp* fx_make_lib_oberheim_hpf(void* mem) { return new (mem) LibOberheimHpf(); }
size_t fx_size_lib_oberheim_hpf() { return sizeof(LibOberheimHpf); }
