// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-3band-compressor.h"
chdsp* fx_make_lib_3band_compressor(void* mem) { return new (mem) Lib3bandCompressor(); }
size_t fx_size_lib_3band_compressor() { return sizeof(Lib3bandCompressor); }
