// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-moog-ladder.h"
chdsp* fx_make_lib_moog_ladder(void* mem) { return new (mem) LibMoogLadder(); }
size_t fx_size_lib_moog_ladder() { return sizeof(LibMoogLadder); }
