// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-korg35-lpf.h"
chdsp* fx_make_lib_korg35_lpf(void* mem) { return new (mem) LibKorg35Lpf(); }
size_t fx_size_lib_korg35_lpf() { return sizeof(LibKorg35Lpf); }
