// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-tone-stack.h"
chdsp* fx_make_lib_tone_stack(void* mem) { return new (mem) LibToneStack(); }
size_t fx_size_lib_tone_stack() { return sizeof(LibToneStack); }
