// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-kb-rom-rev1.h"
chdsp* fx_make_lib_kb_rom_rev1(void* mem) { return new (mem) LibKbRomRev1(); }
size_t fx_size_lib_kb_rom_rev1() { return sizeof(LibKbRomRev1); }
