// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-echo.h"
chdsp* fx_make_lib_echo(void* mem) { return new (mem) LibEcho(); }
size_t fx_size_lib_echo() { return sizeof(LibEcho); }
