// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-vibrato2.h"
chdsp* fx_make_lib_vibrato2(void* mem) { return new (mem) LibVibrato2(); }
size_t fx_size_lib_vibrato2() { return sizeof(LibVibrato2); }
