// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-fdn-reverb.h"
chdsp* fx_make_lib_fdn_reverb(void* mem) { return new (mem) LibFdnReverb(); }
size_t fx_size_lib_fdn_reverb() { return sizeof(LibFdnReverb); }
