// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-rms-compressor.h"
chdsp* fx_make_lib_rms_compressor(void* mem) { return new (mem) LibRmsCompressor(); }
size_t fx_size_lib_rms_compressor() { return sizeof(LibRmsCompressor); }
