// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-1176.h"
chdsp* fx_make_lib_1176(void* mem) { return new (mem) Lib1176(); }
size_t fx_size_lib_1176() { return sizeof(Lib1176); }
