// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-spectral-tilt.h"
chdsp* fx_make_lib_spectral_tilt(void* mem) { return new (mem) LibSpectralTilt(); }
size_t fx_size_lib_spectral_tilt() { return sizeof(LibSpectralTilt); }
