// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lib-autowah.h"
chdsp* fx_make_lib_autowah(void* mem) { return new (mem) LibAutowah(); }
size_t fx_size_lib_autowah() { return sizeof(LibAutowah); }
