// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/lofi-bitcrush.h"
chdsp* fx_make_lofi_bitcrush(void* mem) { return new (mem) LofiBitcrush(); }
size_t fx_size_lofi_bitcrush() { return sizeof(LofiBitcrush); }
