// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/luca-chamberlin.h"
chdsp* fx_make_luca_chamberlin(void* mem) { return new (mem) LucaChamberlin(); }
size_t fx_size_luca_chamberlin() { return sizeof(LucaChamberlin); }
