// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/luca-greisinger-480l.h"
chdsp* fx_make_luca_greisinger_480l(void* mem) { return new (mem) LucaGreisinger480l(); }
size_t fx_size_luca_greisinger_480l() { return sizeof(LucaGreisinger480l); }
