// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/mag-constant-detune-chorus.h"
chdsp* fx_make_mag_constant_detune_chorus(void* mem) { return new (mem) MagConstantDetuneChorus(); }
size_t fx_size_mag_constant_detune_chorus() { return sizeof(MagConstantDetuneChorus); }
