// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/mag-character-compressor.h"
chdsp* fx_make_mag_character_compressor(void* mem) { return new (mem) MagCharacterCompressor(); }
size_t fx_size_mag_character_compressor() { return sizeof(MagCharacterCompressor); }
