// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/multi-phaser.h"
chdsp* fx_make_multi_phaser(void* mem) { return new (mem) MultiPhaser(); }
size_t fx_size_multi_phaser() { return sizeof(MultiPhaser); }
