// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/owl-sweep-wah.h"
chdsp* fx_make_owl_sweep_wah(void* mem) { return new (mem) OwlSweepWah(); }
size_t fx_size_owl_sweep_wah() { return sizeof(OwlSweepWah); }
