// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/owl-qompander.h"
chdsp* fx_make_owl_qompander(void* mem) { return new (mem) OwlQompander(); }
size_t fx_size_owl_qompander() { return sizeof(OwlQompander); }
