// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/owl-smooth-delay.h"
chdsp* fx_make_owl_smooth_delay(void* mem) { return new (mem) OwlSmoothDelay(); }
size_t fx_size_owl_smooth_delay() { return sizeof(OwlSmoothDelay); }
