// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/pitch-octaver.h"
chdsp* fx_make_pitch_octaver(void* mem) { return new (mem) PitchOctaver(); }
size_t fx_size_pitch_octaver() { return sizeof(PitchOctaver); }
