// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/resonant-dj-filter.h"
chdsp* fx_make_resonant_dj_filter(void* mem) { return new (mem) ResonantDjFilter(); }
size_t fx_size_resonant_dj_filter() { return sizeof(ResonantDjFilter); }
