// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/reverse-delay.h"
chdsp* fx_make_reverse_delay(void* mem) { return new (mem) ReverseDelay(); }
size_t fx_size_reverse_delay() { return sizeof(ReverseDelay); }
