// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/ring-mod-percussion.h"
chdsp* fx_make_ring_mod_percussion(void* mem) { return new (mem) RingModPercussion(); }
size_t fx_size_ring_mod_percussion() { return sizeof(RingModPercussion); }
