// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/silicon-fuzz.h"
chdsp* fx_make_silicon_fuzz(void* mem) { return new (mem) SiliconFuzz(); }
size_t fx_size_silicon_fuzz() { return sizeof(SiliconFuzz); }
