// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/spring-reverb.h"
chdsp* fx_make_spring_reverb(void* mem) { return new (mem) SpringReverb(); }
size_t fx_size_spring_reverb() { return sizeof(SpringReverb); }
