// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/stereo-pingpong-beat.h"
chdsp* fx_make_stereo_pingpong_beat(void* mem) { return new (mem) StereoPingpongBeat(); }
size_t fx_size_stereo_pingpong_beat() { return sizeof(StereoPingpongBeat); }
