// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/sub-resonator.h"
chdsp* fx_make_sub_resonator(void* mem) { return new (mem) SubResonator(); }
size_t fx_size_sub_resonator() { return sizeof(SubResonator); }
