// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tape-saturation-drum.h"
chdsp* fx_make_tape_saturation_drum(void* mem) { return new (mem) TapeSaturationDrum(); }
size_t fx_size_tape_saturation_drum() { return sizeof(TapeSaturationDrum); }
