// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tape-delay.h"
chdsp* fx_make_tape_delay(void* mem) { return new (mem) TapeDelay(); }
size_t fx_size_tape_delay() { return sizeof(TapeDelay); }
