// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-shimmizita.h"
chdsp* fx_make_tdg_shimmizita(void* mem) { return new (mem) TdgShimmizita(); }
size_t fx_size_tdg_shimmizita() { return sizeof(TdgShimmizita); }
