// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-delay-flange.h"
chdsp* fx_make_tdg_delay_flange(void* mem) { return new (mem) TdgDelayFlange(); }
size_t fx_size_tdg_delay_flange() { return sizeof(TdgDelayFlange); }
