// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-duck-reverb.h"
chdsp* fx_make_tdg_duck_reverb(void* mem) { return new (mem) TdgDuckReverb(); }
size_t fx_size_tdg_duck_reverb() { return sizeof(TdgDuckReverb); }
