// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-delay-ps.h"
chdsp* fx_make_tdg_delay_ps(void* mem) { return new (mem) TdgDelayPs(); }
size_t fx_size_tdg_delay_ps() { return sizeof(TdgDelayPs); }
