// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-delay-duck.h"
chdsp* fx_make_tdg_delay_duck(void* mem) { return new (mem) TdgDelayDuck(); }
size_t fx_size_tdg_delay_duck() { return sizeof(TdgDelayDuck); }
