// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-room-simulator.h"
chdsp* fx_make_tdg_room_simulator(void* mem) { return new (mem) TdgRoomSimulator(); }
size_t fx_size_tdg_room_simulator() { return sizeof(TdgRoomSimulator); }
