// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-delay-colored.h"
chdsp* fx_make_tdg_delay_colored(void* mem) { return new (mem) TdgDelayColored(); }
size_t fx_size_tdg_delay_colored() { return sizeof(TdgDelayColored); }
