// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-multi-tap-echo.h"
chdsp* fx_make_tdg_multi_tap_echo(void* mem) { return new (mem) TdgMultiTapEcho(); }
size_t fx_size_tdg_multi_tap_echo() { return sizeof(TdgMultiTapEcho); }
