// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-shimmer.h"
chdsp* fx_make_tdg_shimmer(void* mem) { return new (mem) TdgShimmer(); }
size_t fx_size_tdg_shimmer() { return sizeof(TdgShimmer); }
