// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-delay-ringmod.h"
chdsp* fx_make_tdg_delay_ringmod(void* mem) { return new (mem) TdgDelayRingmod(); }
size_t fx_size_tdg_delay_ringmod() { return sizeof(TdgDelayRingmod); }
