// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-delay-detune.h"
chdsp* fx_make_tdg_delay_detune(void* mem) { return new (mem) TdgDelayDetune(); }
size_t fx_size_tdg_delay_detune() { return sizeof(TdgDelayDetune); }
