// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-delay-wah.h"
chdsp* fx_make_tdg_delay_wah(void* mem) { return new (mem) TdgDelayWah(); }
size_t fx_size_tdg_delay_wah() { return sizeof(TdgDelayWah); }
