// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-delay-emu.h"
chdsp* fx_make_tdg_delay_emu(void* mem) { return new (mem) TdgDelayEmu(); }
size_t fx_size_tdg_delay_emu() { return sizeof(TdgDelayEmu); }
