// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-rotary-speakers.h"
chdsp* fx_make_tdg_rotary_speakers(void* mem) { return new (mem) TdgRotarySpeakers(); }
size_t fx_size_tdg_rotary_speakers() { return sizeof(TdgRotarySpeakers); }
