// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-parametric-pitch-shifter.h"
chdsp* fx_make_tdg_parametric_pitch_shifter(void* mem) { return new (mem) TdgParametricPitchShifter(); }
size_t fx_size_tdg_parametric_pitch_shifter() { return sizeof(TdgParametricPitchShifter); }
