// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-freeverb3.h"
chdsp* fx_make_tdg_freeverb3(void* mem) { return new (mem) TdgFreeverb3(); }
size_t fx_size_tdg_freeverb3() { return sizeof(TdgFreeverb3); }
