// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/tdg-tri-chorus.h"
chdsp* fx_make_tdg_tri_chorus(void* mem) { return new (mem) TdgTriChorus(); }
size_t fx_size_tdg_tri_chorus() { return sizeof(TdgTriChorus); }
