// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/transient-shaper.h"
chdsp* fx_make_transient_shaper(void* mem) { return new (mem) TransientShaper(); }
size_t fx_size_transient_shaper() { return sizeof(TransientShaper); }
