// GENERATED by tools/build-firmware.mjs — do not edit.
#include <new>
#include "daisy_seed.h"
#include "chameleon_faust.h"
#include "faust/wavefolder-dirt.h"
chdsp* fx_make_wavefolder_dirt(void* mem) { return new (mem) WavefolderDirt(); }
size_t fx_size_wavefolder_dirt() { return sizeof(WavefolderDirt); }
