#!/usr/bin/env python3
"""
gx-port.py — port guitarix Faust circuit simulations to pure Faust.

Guitarix's DK-method pedal/amp sims are Faust, but their nonlinearities (diode/transistor/tube
curves) are C++ lookup tables reached through `ffunction`, which the browser/wasm compiler can't
call. This tool reads those tables straight out of the guitarix tree and emits:

  dsp/lib/gx_tables.lib   every table as a Faust `waveform` + the exact lookup semantics of the C code
  dsp/lib/guitarix.lib    guitarix.lib / trany.lib / redeye.lib with ffunction/fconstant lines replaced
  dsp/lib/trany.lib
  dsp/lib/redeye.lib
  dsp/lib/clipping.lib    the clipping.h family (asymclip/opamp/symclip...) as Faust

and ports individual effect files:

  python3 tools/port/gx-port.py --libs                   # regenerate the libs
  python3 tools/port/gx-port.py bossds1 fuzzface ...     # port trunk/src/LV2/faust/<name>.dsp -> dsp/gx-<name>.dsp

Set GUITARIX=/path/to/guitarix/trunk (default: /home/claude/chameleon/ext/brummer10_guitarix/trunk).
Licence of everything emitted: GPL-2.0-or-later (guitarix).
"""
import os, re, sys, glob, json

GX = os.environ.get('GUITARIX', '/home/claude/chameleon/ext/brummer10_guitarix/trunk')
SRC = os.path.join(GX, 'src')
DSPD = os.path.join(SRC, 'LV2', 'DSP')
FAUSTD = os.path.join(SRC, 'LV2', 'faust')
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
LIBOUT = os.path.join(ROOT, 'dsp', 'lib')
os.makedirs(LIBOUT, exist_ok=True)

NUM = r'[-+]?(?:\d+\.\d*|\.\d+|\d+)(?:[eE][-+]?\d+)?'

def fmt(v):
    s = repr(float(v))
    return s if ('e' in s or '.' in s) else s + '.0'

def parse_tables(text):
    """Return list of dicts {name, index, low, high, istep, size, data} for every table1d(_imp) initialiser."""
    out = []
    # e.g. "static table1d_imp<2001> tubetable_12AX7[2] __rt_data = { { // Ri = 68k\n -5,5,200,2001, {" or
    #      "static tablecopicat1_neg_imp<2048> copicat1_neg_table __rt_data = {\n 0,1.5,24.12,2048, {"
    for m in re.finditer(r'(\w+)\s*(\[(\d+)\])?\s*(?:__rt_data)?\s*=\s*\{', text):
        name, arr = m.group(1), m.group(3)
        pos = m.end()
        n = int(arr) if arr else 1
        for idx in range(n):
            hm = re.compile(r'\{?\s*(?://[^\n]*\n\s*)?(' + NUM + r')\s*,\s*(' + NUM + r')\s*,\s*(' + NUM + r')\s*,\s*(\d+)\s*,\s*\{').search(text, pos)
            if not hm: break
            low, high, istep, size = float(hm.group(1)), float(hm.group(2)), float(hm.group(3)), int(hm.group(4))
            start = hm.end(); end = text.index('}', start)
            data = [float(x) for x in re.findall(NUM, text[start:end])]
            if len(data) != size:
                # some tables have size-1 entries declared; trust the data
                pass
            out.append({'name': name, 'index': idx, 'low': low, 'high': high, 'istep': istep, 'size': len(data), 'data': data})
            pos = end + 1
    return out

def waveform(name, data):
    rows = []
    for i in range(0, len(data), 8):
        rows.append('  ' + ','.join(fmt(v) for v in data[i:i + 8]))
    return f'{name} = waveform{{\n' + ',\n'.join(rows) + '\n};\n'

def emit_tables():
    L = ['// GENERATED by tools/port/gx-port.py from the guitarix source tree — do not edit.',
         '// Copyright (C) guitarix project (Hermann Meyer, Andreas Degert, James Warden, Pete Shorthose).',
         '// Licence: GPL-2.0-or-later.', 'declare license "GPL-2.0-or-later";', 'import("stdfaust.lib");', '',
         '// Generic linear-interpolated table lookup replicating guitarix\'s table1d code:',
         '//   f = (x - low) * istep; i = int(f); clamp to [0, size-1]; lerp between data[i] and data[i+1].',
         'gx_lut(tbl, n, low, istep, x) = select2(i < 0, select2(i >= n - 1, v0 * (1 - fr) + v1 * fr, last), first)',
         'with {',
         '  fr0 = (x - low) * istep;',
         '  f = select2(ma.isnan(fr0) | ma.isinf(fr0), fr0, 0) : max(-1) : min(n + 1);   // NaN/inf would trap int() in wasm',
         '  i = int(f);',
         '  ic = max(0, min(n - 2, i));',
         '  fr = f - ic;',
         '  rd(k) = (tbl, k) : rdtable;',
         '  v0 = rd(ic); v1 = rd(ic + 1);',
         '  first = rd(0); last = rd(n - 1);',
         '};', '']
    # 1. circuit clip tables
    circuit = {}
    for h in sorted(glob.glob(os.path.join(DSPD, 'circuit_tables', '*_table.h'))):
        txt = open(h).read()
        for t in parse_tables(txt):
            tname = t['name']            # e.g. copicat1_table or copicat1_neg_table
            base = tname.replace('_table', '')
            wf = f'gx_wf_{base}'
            L.append(waveform(wf, t['data']))
            # C: f = fabs(x) * istep (low is 0 for these) ; return copysign(f, x)
            fn = base.replace('_neg', '_negclip') if base.endswith('_neg') else base + 'clip'
            L.append(f'{fn}(x) = ma.copysign(gx_lut({wf}, {t["size"]}, {fmt(t["low"])}, {fmt(t["istep"])}, abs(x)), x);\n')
            circuit[fn] = wf
    # 2. ts9 table
    ts9 = os.path.join(SRC, 'plugins', 'ts9nonlin.cc')
    if os.path.exists(ts9):
        t = parse_tables(open(ts9).read())[0]
        L.append(waveform('gx_wf_ts9', t['data']))
        # C: f = (fabs(x)/(3+fabs(x)) - low) * istep ; return copysign(f, -x)
        L.append(f'ts9nonlin(x) = ma.copysign(gx_lut(gx_wf_ts9, {t["size"]}, {fmt(t["low"])}, {fmt(t["istep"])}, abs(x) / (3.0 + abs(x))), 0 - x);\n')
    # 3. clipping.h tables (clipt*.cc): cliptable[10] ordering
    ct = []
    for fn in ['clipt.cc', 'clipt2.cc', 'clipt3.cc', 'clipt1.cc', 'clipt4.cc']:
        p = os.path.join(FAUSTD, fn)
        if os.path.exists(p): ct += parse_tables(open(p).read())
    for k, t in enumerate(ct):
        L.append(waveform(f'gx_wf_clip{k}', t['data']))
        L.append(f'gx_clipmeta{k} = ({t["size"]}, {fmt(t["low"])}, {fmt(t["istep"])});\n')
    # 4. tube tables (valve.h order) and trany tables
    tubes = ['12AX7', '6V6', '12AU7', '6DJ8', '12AT7', '6C16', '6L6CG', 'EL34', '12AY7', 'JJECC83S', 'JJECC99', 'EL84', 'EF86', 'SVEL34']
    tube_f, tube_r = [], []
    for tb in tubes:
        p = None
        for cand in [tb + '.cc', tb.lower() + '.cc']:
            if os.path.exists(os.path.join(DSPD, 'tube_tables', cand)): p = os.path.join(DSPD, 'tube_tables', cand)
        if not p: raise SystemExit('missing tube table ' + tb)
        ts = parse_tables(open(p).read())
        f = [t for t in ts if t['name'] == f'tubetable_{tb}']; r = [t for t in ts if t['name'] == f'tubetable2_{tb}']
        for i in range(2):
            L.append(waveform(f'gx_wf_tube_{tb}_{i}', f[i]['data'])); tube_f.append((f'gx_wf_tube_{tb}_{i}', f[i]))
            if r:  # 6L6CG has no Ranode table in guitarix (commented out in valve.h) — tubetab2 indices shift, replicate that
                L.append(waveform(f'gx_wf_ranode_{tb}_{i}', r[i]['data'])); tube_r.append((f'gx_wf_ranode_{tb}_{i}', r[i]))
    names = []
    for tb in tubes: names += [f'TB_{tb}_68k', f'TB_{tb}_250k']
    for i, n in enumerate(names): L.append(f'{n} = {i};')
    L.append('')
    def selector(fname, tabs):
        L.append(f'{fname}(tb, x) = ba.selectn({len(tabs)}, tb, ' + ', '.join(f'gx_lut({w}, {t["size"]}, {fmt(t["low"])}, {fmt(t["istep"])}, x)' for w, t in tabs) + ');')
    while len(tube_r) < len(tube_f): tube_r.append(tube_r[-1])   # pad like the null-terminated C array (never hit in practice)
    selector('Ftube', tube_f); selector('Ranode', tube_r); L.append('')
    tr_f, tr_r = [], []
    for tb in ['KT88', '7199P']:
        tr = parse_tables(open(os.path.join(DSPD, 'tube_tables', tb + '.cc')).read())
        f = [t for t in tr if t['name'] == f'tubetable_{tb}']; r = [t for t in tr if t['name'] == f'tubetable2_{tb}']
        for i in range(2):
            L.append(waveform(f'gx_wf_trany_{tb}_{i}', f[i]['data'])); L.append(waveform(f'gx_wf_rtrany_{tb}_{i}', r[i]['data']))
            tr_f.append((f'gx_wf_trany_{tb}_{i}', f[i])); tr_r.append((f'gx_wf_rtrany_{tb}_{i}', r[i]))
    for i, n in enumerate(['TB_KT88_68k', 'TB_KT88_250k', 'TB_7199P_68k', 'TB_7199P_250k']): L.append(f'TRANY_{n} = {i};')
    selector('Ftrany', tr_f); selector('Rtrany', tr_r)
    L.append('')
    open(os.path.join(LIBOUT, 'gx_tables.lib'), 'w').write('\n'.join(L))
    # clipping.lib — the clipping.h functions
    C = ['// GENERATED by tools/port/gx-port.py — guitarix clipping.h as Faust. GPL-2.0-or-later.', 'declare license "GPL-2.0-or-later";', 'import("stdfaust.lib");', 'gxt = library("gx_tables.lib");', '',
         '// warp modes: 0 = f/(3+f) - low ; 1 = f (no low) ; 2 = f - low',
         'gx_clip(tp, tn, warp, sgn, x) = ma.copysign(v, sgn * x) with {',
         '  f = abs(x);',
         '  w0(n, low, istep) = (f / (3.0 + f) - low) * istep;',
         '  w1(n, low, istep) = f * istep;',
         '  w2(n, low, istep) = (f - low) * istep;',
         '  look(k, n, low, istep) = gxt.gx_lut(k, n, 0, 1, select3(warp, w0(n, low, istep), w1(n, low, istep), w2(n, low, istep)));',
         '  v = select2(x < 0, look(tp, gxt.gx_clipmeta_p), look(tn, gxt.gx_clipmeta_n));',
         '};', '']
    # simpler: emit each function explicitly with its own tables
    C = ['// GENERATED by tools/port/gx-port.py — guitarix clipping.h as Faust. GPL-2.0-or-later.', 'declare license "GPL-2.0-or-later";', 'import("stdfaust.lib");', 'gxt = library("gx_tables.lib");', '']
    src = open(os.path.join(FAUSTD, 'clipping.h')).read()
    for m in re.finditer(r'static inline double (\w+)\(double x\) \{(.*?)\n\}', src, re.S):
        fname, body = m.group(1), m.group(2)
        tab = int(re.search(r'int table = (\d+);', body).group(1))
        neg = re.search(r'if \(x<0\) table = (\d+);', body)
        tneg = int(neg.group(1)) if neg else tab
        warp = re.search(r'f = \((.*?)\) \* clip\.istep;', body).group(1).replace(' ', '')
        sgn = '-1' if 'copysign(f, -x)' in body else '1'
        def look(k):
            t = ct[k]
            if warp == 'f/(3.0+f)-clip.low': arg = f'(f / (3.0 + f) - {fmt(t["low"])}) * {fmt(t["istep"])}'
            elif warp == 'f': arg = f'f * {fmt(t["istep"])}'
            elif warp == 'f-clip.low': arg = f'(f - {fmt(t["low"])}) * {fmt(t["istep"])}'
            else: raise SystemExit('unknown warp ' + warp)
            return f'gxt.gx_lut(gxt.gx_wf_clip{k}, {t["size"]}, 0, 1, {arg})'
        C.append(f'{fname}(x) = ma.copysign(select2(x < 0, {look(tab)}, {look(tneg)}), {sgn} * x) with {{ f = abs(x); }};')
    open(os.path.join(LIBOUT, 'clipping.lib'), 'w').write('\n'.join(C) + '\n')
    return circuit

FF_RE = re.compile(r'^\s*(\w+)\s*=\s*ffunction\((.*?)\);\s*$', re.M)
FC_RE = re.compile(r'^\s*(\w+)\s*=\s*fconstant\(int (\w+),\s*"[^"]+"\);\s*$', re.M)

def port_text(text, filename='?'):
    """Replace ffunction/fconstant with pure-Faust equivalents. Returns (text, needs_tables, needs_clipping)."""
    needs_t = needs_c = False
    def ff(m):
        nonlocal needs_t, needs_c
        alias, sig = m.group(1), m.group(2)
        cname = re.search(r'\w+\s+(\w+)\(', sig).group(1)
        if cname == 'signbit': return f'{alias}(x) = (x < 0);'
        if cname == 'copysign': return f'{alias} = ma.copysign;'
        if cname == 'fold': return f'{alias}(x, y) = ma.fmod(x, y);'  # not used by ported set; placeholder
        if cname in ('Ftube', 'Ranode', 'Ftrany', 'Rtrany'): needs_t = True; return f'{alias} = gxt.{cname};'
        if cname == 'ts9nonlin': needs_t = True; return f'{alias} = gxt.ts9nonlin;'
        if cname.endswith('clip') and 'table.h' in sig: needs_t = True; return f'{alias} = gxt.{cname};'
        if 'clipping.h' in sig: needs_c = True; return f'{alias} = gxc.{cname};'
        if cname == 'B2N': return f'{alias}(n, bpm) = 60.0 / bpm * pow(2.0, n);'
        raise SystemExit(f'{filename}: unhandled ffunction {sig}')
    text = FF_RE.sub(ff, text)
    def fc(m):
        nonlocal needs_t
        alias, cname = m.group(1), m.group(2)
        needs_t = True
        if cname.startswith('TUBE_TABLE_'): return f'{alias} = gxt.TB_{cname[len("TUBE_TABLE_"):]};'
        if cname.startswith('TRANY_TABLE_'): return f'{alias} = gxt.TRANY_TB_{cname[len("TRANY_TABLE_"):]};'
        raise SystemExit(f'{filename}: unhandled fconstant {cname}')
    text = FC_RE.sub(fc, text)
    # The C functions were 1-arg ffunctions, so guitarix writes `clip(_)` / `opamp(X2-_)`. Our pure-Faust
    # versions are abstractions whose parameter is used several times, and Faust replicates an explicit
    # `_` argument per use. Rewrite `alias(EXPR)` -> `(EXPR : alias)` whenever EXPR contains a wire.
    aliases = [m.group(1) for m in FF_RE.finditer(open(filename).read())] if os.path.exists(filename) else []
    aliases += re.findall(r'^\s*(\w+)\s*=\s*gx[tc]\.\w+;', text, re.M)
    for a in set(aliases):
        text = rewrite_calls(text, a)
    return text, needs_t, needs_c

def rewrite_calls(text, name):
    out, i = [], 0
    pat = re.compile(r'\b' + re.escape(name) + r'\(')
    while True:
        m = pat.search(text, i)
        if not m: out.append(text[i:]); break
        out.append(text[i:m.start()])
        depth, j = 1, m.end()
        while j < len(text) and depth: depth += {'(': 1, ')': -1}.get(text[j], 0); j += 1
        inner = text[m.end():j - 1]
        if re.search(r'(?<![\w.])_(?![\w.])', inner): out.append(f'({inner} : {name})')
        else: out.append(text[m.start():j])
        i = j
    return ''.join(out)

def with_imports(text, needs_t, needs_c):
    head = ''
    if needs_t: head += 'gxt = library("gx_tables.lib");\n'
    if needs_c: head += 'gxc = library("clipping.lib");\n'
    if not head: return text
    # insert after the last import(...) line
    ms = list(re.finditer(r'^\s*import\(.*?\);\s*$', text, re.M))
    if ms: i = ms[-1].end(); return text[:i] + '\n' + head + text[i:]
    return head + text

def emit_libs():
    emit_tables()
    for lib in ['guitarix.lib', 'trany.lib', 'redeye.lib']:
        src = open(os.path.join(FAUSTD, lib)).read()
        t, nt, nc = port_text(src, lib)
        t = with_imports(t, nt, nc)
        hdr = f'// PORTED by tools/port/gx-port.py from guitarix trunk/src/LV2/faust/{lib} (GPL-2.0-or-later).\n// C++ lookup tables replaced by pure Faust tables from gx_tables.lib.\n'
        open(os.path.join(LIBOUT, lib), 'w').write(hdr + t)
    print('libs written to', LIBOUT)

def port_effect(name, _seen=set()):
    if name in _seen: return None
    _seen.add(name)
    src_path = None
    for cand in [os.path.join(FAUSTD, name + '.dsp'), os.path.join(SRC, 'plugins', name + '.dsp'), os.path.join(SRC, 'faust', name + '.dsp')]:
        if os.path.exists(cand): src_path = cand; break
    if not src_path: raise SystemExit('not found: ' + name)
    text = open(src_path).read()
    t, nt, nc = port_text(text, name)
    t = with_imports(t, nt, nc)
    # component("x.dsp") -> port x too and point at the ported copy (found via the dsp/lib include path)
    def comp(m):
        dep = m.group(1)
        try: port_effect(dep)
        except SystemExit as e: print('  dependency failed:', dep, e)
        return f'component("gx-{dep.replace("_", "-")}.dsp")'
    t = re.sub(r'component\("(\w+)\.dsp"\)', comp, t)
    has_process = re.search(r'^\s*process\s*(\(|=)', t, re.M) is not None
    out = os.path.join(ROOT, 'dsp' if has_process else 'dsp/lib', f'gx-{name.replace("_", "-")}.dsp')
    hdr = f'// PORTED by tools/port/gx-port.py from guitarix {os.path.relpath(src_path, GX)} (GPL-2.0-or-later).\n'
    if 'declare license' not in t: hdr += 'declare license "GPL-2.0-or-later";\n'
    hdr += 'declare chameleon_flags "-double";   // DK circuit sims are numerically unstable in single precision\n'
    open(out, 'w').write(hdr + t)
    return out

if __name__ == '__main__':
    args = sys.argv[1:]
    if not args or args[0] == '--libs':
        emit_libs(); args = args[1:]
    for a in args: print('ported', port_effect(a))
