#!/usr/bin/env node
/**
 * build-icons.mjs — bundle the Tabler icons (via @iconify-json/tabler) the app uses into js/icons.js,
 * so the studio needs no runtime icon API. Scans index.html, compare/index.html, js/app.js,
 * dsp/catalog.json and tools/build-catalog.mjs for `tabler:<name>` references.
 *
 *   npm install @iconify-json/tabler   (dev only)
 *   node tools/build-icons.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
let set;
try { set = require('@iconify-json/tabler/icons.json'); }
catch (e) { console.error('Run: npm install @iconify-json/tabler'); process.exit(1); }

const files = ['index.html', 'compare/index.html', 'js/app.js', 'dsp/catalog.json', 'tools/build-catalog.mjs'].map(f => path.join(root, f)).filter(fs.existsSync);
const names = new Set();
for (const f of files) for (const m of fs.readFileSync(f, 'utf8').matchAll(/tabler:([a-z0-9-]+)/g)) names.add(m[1]);

const out = {};
const missing = [];
for (const n of [...names].sort()) {
  const ic = set.icons[n] || (set.aliases && set.aliases[n] && set.icons[set.aliases[n].parent]);
  if (!ic) { missing.push(n); continue; }
  out[n] = { body: ic.body, w: ic.width || set.width || 24, h: ic.height || set.height || 24 };
}
if (missing.length) { console.error('Unknown tabler icons:', missing.join(', ')); process.exit(1); }

const js = `/**
 * GENERATED by tools/build-icons.mjs — Tabler Icons (MIT, https://tabler.io/icons) via Iconify.
 * ${Object.keys(out).length} icons. Use: icon('tabler:wave-sine') -> SVG string.
 */
const ICONS = ${JSON.stringify(out)};
function icon(name, cls = '') {
  const n = String(name).replace(/^tabler:/, '');
  const ic = ICONS[n];
  if (!ic) return '<svg class="ico ' + cls + '" viewBox="0 0 24 24" width="1em" height="1em"><circle cx="12" cy="12" r="9" fill="none" stroke="currentColor" stroke-width="2"/></svg>';
  return '<svg class="ico ' + cls + '" viewBox="0 0 ' + ic.w + ' ' + ic.h + '" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + ic.body + '</svg>';
}
`;
fs.writeFileSync(path.join(root, 'js/icons.js'), js);
console.log(`Wrote js/icons.js with ${Object.keys(out).length} icons: ${Object.keys(out).join(', ')}`);
