// GENERATED by tools/build-firmware.mjs — do not edit. Every effect in js/effects-data.js, catalog order.
#pragma once
#include <cstddef>
#include "chameleon_faust.h"

chdsp* fx_make_tape_delay(void*); size_t fx_size_tape_delay();
chdsp* fx_make_dattorro_plate(void*); size_t fx_size_dattorro_plate();
chdsp* fx_make_bbd_chorus(void*); size_t fx_size_bbd_chorus();
chdsp* fx_make_harmonic_tremolo(void*); size_t fx_size_harmonic_tremolo();
chdsp* fx_make_dynamic_overdrive(void*); size_t fx_size_dynamic_overdrive();
chdsp* fx_make_klon_centaur(void*); size_t fx_size_klon_centaur();
chdsp* fx_make_infinite_compressor(void*); size_t fx_size_infinite_compressor();
chdsp* fx_make_multi_phaser(void*); size_t fx_size_multi_phaser();
chdsp* fx_make_silicon_fuzz(void*); size_t fx_size_silicon_fuzz();
chdsp* fx_make_auto_wah(void*); size_t fx_size_auto_wah();
chdsp* fx_make_pitch_octaver(void*); size_t fx_size_pitch_octaver();
chdsp* fx_make_analog_flanger(void*); size_t fx_size_analog_flanger();
chdsp* fx_make_spring_reverb(void*); size_t fx_size_spring_reverb();
chdsp* fx_make_clean_boost(void*); size_t fx_size_clean_boost();
chdsp* fx_make_reverse_delay(void*); size_t fx_size_reverse_delay();
chdsp* fx_make_lofi_bitcrush(void*); size_t fx_size_lofi_bitcrush();
chdsp* fx_make_drum_pumping_comp(void*); size_t fx_size_drum_pumping_comp();
chdsp* fx_make_gated_snare_reverb(void*); size_t fx_size_gated_snare_reverb();
chdsp* fx_make_resonant_dj_filter(void*); size_t fx_size_resonant_dj_filter();
chdsp* fx_make_tape_saturation_drum(void*); size_t fx_size_tape_saturation_drum();
chdsp* fx_make_beat_repeater(void*); size_t fx_size_beat_repeater();
chdsp* fx_make_sub_resonator(void*); size_t fx_size_sub_resonator();
chdsp* fx_make_drum_slammer(void*); size_t fx_size_drum_slammer();
chdsp* fx_make_ring_mod_percussion(void*); size_t fx_size_ring_mod_percussion();
chdsp* fx_make_transient_shaper(void*); size_t fx_size_transient_shaper();
chdsp* fx_make_stereo_pingpong_beat(void*); size_t fx_size_stereo_pingpong_beat();
chdsp* fx_make_wavefolder_dirt(void*); size_t fx_size_wavefolder_dirt();
chdsp* fx_make_comb_resonator(void*); size_t fx_size_comb_resonator();
chdsp* fx_make_freq_shifter(void*); size_t fx_size_freq_shifter();
chdsp* fx_make_bbd_drum_delay(void*); size_t fx_size_bbd_drum_delay();
chdsp* fx_make_expander_gate(void*); size_t fx_size_expander_gate();
chdsp* fx_make_lib_12ax7_preamp(void*); size_t fx_size_lib_12ax7_preamp();
chdsp* fx_make_gx_gx_studiopre(void*); size_t fx_size_gx_gx_studiopre();
chdsp* fx_make_gx_gxamp15(void*); size_t fx_size_gx_gxamp15();
chdsp* fx_make_gx_gxamp16(void*); size_t fx_size_gx_gxamp16();
chdsp* fx_make_gx_gxamp14(void*); size_t fx_size_gx_gxamp14();
chdsp* fx_make_gx_gxamp17(void*); size_t fx_size_gx_gxamp17();
chdsp* fx_make_gx_gxamp4(void*); size_t fx_size_gx_gxamp4();
chdsp* fx_make_gx_gxamp8(void*); size_t fx_size_gx_gxamp8();
chdsp* fx_make_gx_gxamp3(void*); size_t fx_size_gx_gxamp3();
chdsp* fx_make_gx_gxamp11(void*); size_t fx_size_gx_gxamp11();
chdsp* fx_make_gx_gxamp5(void*); size_t fx_size_gx_gxamp5();
chdsp* fx_make_gx_gxamp7(void*); size_t fx_size_gx_gxamp7();
chdsp* fx_make_gx_gxamp(void*); size_t fx_size_gx_gxamp();
chdsp* fx_make_gx_gxamp9(void*); size_t fx_size_gx_gxamp9();
chdsp* fx_make_gx_gxamp18(void*); size_t fx_size_gx_gxamp18();
chdsp* fx_make_gx_gxamp12(void*); size_t fx_size_gx_gxamp12();
chdsp* fx_make_gx_gxamp6(void*); size_t fx_size_gx_gxamp6();
chdsp* fx_make_gx_gxamp10(void*); size_t fx_size_gx_gxamp10();
chdsp* fx_make_gx_gxamp13(void*); size_t fx_size_gx_gxamp13();
chdsp* fx_make_gx_gxamp2(void*); size_t fx_size_gx_gxamp2();
chdsp* fx_make_gx_tube(void*); size_t fx_size_gx_tube();
chdsp* fx_make_ex_guitarix_amp(void*); size_t fx_size_ex_guitarix_amp();
chdsp* fx_make_kpp_tubeamp(void*); size_t fx_size_kpp_tubeamp();
chdsp* fx_make_gx_gxmetal_amp(void*); size_t fx_size_gx_gxmetal_amp();
chdsp* fx_make_gx_gxmetal_head(void*); size_t fx_size_gx_gxmetal_head();
chdsp* fx_make_gx_preamp(void*); size_t fx_size_gx_preamp();
chdsp* fx_make_gx_gx_bigchump(void*); size_t fx_size_gx_gx_bigchump();
chdsp* fx_make_gx_gx_chump(void*); size_t fx_size_gx_gx_chump();
chdsp* fx_make_gx_gx_vibrochump(void*); size_t fx_size_gx_gx_vibrochump();
chdsp* fx_make_gx_reso_tube(void*); size_t fx_size_gx_reso_tube();
chdsp* fx_make_gx_tube3(void*); size_t fx_size_gx_tube3();
chdsp* fx_make_gx_valve(void*); size_t fx_size_gx_valve();
chdsp* fx_make_gx_gx_w20(void*); size_t fx_size_gx_gx_w20();
chdsp* fx_make_lib_adaa_drive(void*); size_t fx_size_lib_adaa_drive();
chdsp* fx_make_gx_astrofuzz(void*); size_t fx_size_gx_astrofuzz();
chdsp* fx_make_gx_axface(void*); size_t fx_size_gx_axface();
chdsp* fx_make_barabas_tubescreamer(void*); size_t fx_size_barabas_tubescreamer();
chdsp* fx_make_gx_bfuzz(void*); size_t fx_size_gx_bfuzz();
chdsp* fx_make_gx_bmp(void*); size_t fx_size_gx_bmp();
chdsp* fx_make_gx_bossds1(void*); size_t fx_size_gx_bossds1();
chdsp* fx_make_gx_buzz(void*); size_t fx_size_gx_buzz();
chdsp* fx_make_gx_coverd(void*); size_t fx_size_gx_coverd();
chdsp* fx_make_gx_cstb(void*); size_t fx_size_gx_cstb();
chdsp* fx_make_lib_cubicnl(void*); size_t fx_size_lib_cubicnl();
chdsp* fx_make_gx_rangem(void*); size_t fx_size_gx_rangem();
chdsp* fx_make_gx_ruin(void*); size_t fx_size_gx_ruin();
chdsp* fx_make_gx_eldist(void*); size_t fx_size_gx_eldist();
chdsp* fx_make_gx_ffreak(void*); size_t fx_size_gx_ffreak();
chdsp* fx_make_gx_foxeylady(void*); size_t fx_size_gx_foxeylady();
chdsp* fx_make_gx_fuzzfacefm(void*); size_t fx_size_gx_fuzzfacefm();
chdsp* fx_make_gx_fuzzface(void*); size_t fx_size_gx_fuzzface();
chdsp* fx_make_gx_fuzzfacerm(void*); size_t fx_size_gx_fuzzfacerm();
chdsp* fx_make_gx_drive(void*); size_t fx_size_gx_drive();
chdsp* fx_make_gx_hornet(void*); size_t fx_size_gx_hornet();
chdsp* fx_make_gx_ts9sim(void*); size_t fx_size_gx_ts9sim();
chdsp* fx_make_kpp_bluedream(void*); size_t fx_size_kpp_bluedream();
chdsp* fx_make_kpp_distruction(void*); size_t fx_size_kpp_distruction();
chdsp* fx_make_kpp_fuzz(void*); size_t fx_size_kpp_fuzz();
chdsp* fx_make_gx_lpbboost(void*); size_t fx_size_gx_lpbboost();
chdsp* fx_make_gx_muff(void*); size_t fx_size_gx_muff();
chdsp* fx_make_gx_mbclipper(void*); size_t fx_size_gx_mbclipper();
chdsp* fx_make_gx_mbd(void*); size_t fx_size_gx_mbd();
chdsp* fx_make_gx_gx_distortion(void*); size_t fx_size_gx_gx_distortion();
chdsp* fx_make_gx_mxrdist(void*); size_t fx_size_gx_mxrdist();
chdsp* fx_make_gx_overdrive(void*); size_t fx_size_gx_overdrive();
chdsp* fx_make_gx_aclipper(void*); size_t fx_size_gx_aclipper();
chdsp* fx_make_gx_scream(void*); size_t fx_size_gx_scream();
chdsp* fx_make_gx_softclip(void*); size_t fx_size_gx_softclip();
chdsp* fx_make_lib_tape_hysteresis(void*); size_t fx_size_lib_tape_hysteresis();
chdsp* fx_make_gx_buffb(void*); size_t fx_size_gx_buffb();
chdsp* fx_make_gx_fumaster(void*); size_t fx_size_gx_fumaster();
chdsp* fx_make_lib_wavefolder(void*); size_t fx_size_lib_wavefolder();
chdsp* fx_make_lib_1176(void*); size_t fx_size_lib_1176();
chdsp* fx_make_lib_3band_compressor(void*); size_t fx_size_lib_3band_compressor();
chdsp* fx_make_mag_character_compressor(void*); size_t fx_size_mag_character_compressor();
chdsp* fx_make_gx_compressor(void*); size_t fx_size_gx_compressor();
chdsp* fx_make_gx_expander(void*); size_t fx_size_gx_expander();
chdsp* fx_make_lib_expander(void*); size_t fx_size_lib_expander();
chdsp* fx_make_lib_fb_compressor(void*); size_t fx_size_lib_fb_compressor();
chdsp* fx_make_lib_ff_compressor(void*); size_t fx_size_lib_ff_compressor();
chdsp* fx_make_ex_granular_gate(void*); size_t fx_size_ex_granular_gate();
chdsp* fx_make_lib_jos_compressor(void*); size_t fx_size_lib_jos_compressor();
chdsp* fx_make_kpp_deadgate(void*); size_t fx_size_kpp_deadgate();
chdsp* fx_make_lib_lookahead_limiter(void*); size_t fx_size_lib_lookahead_limiter();
chdsp* fx_make_gx_mbc(void*); size_t fx_size_gx_mbc();
chdsp* fx_make_gx_mbcs(void*); size_t fx_size_gx_mbcs();
chdsp* fx_make_lib_gate(void*); size_t fx_size_lib_gate();
chdsp* fx_make_owl_qompander(void*); size_t fx_size_owl_qompander();
chdsp* fx_make_lib_rms_peak_limiter(void*); size_t fx_size_lib_rms_peak_limiter();
chdsp* fx_make_lib_rms_compressor(void*); size_t fx_size_lib_rms_compressor();
chdsp* fx_make_gx_susta(void*); size_t fx_size_gx_susta();
chdsp* fx_make_gx_eq(void*); size_t fx_size_gx_eq();
chdsp* fx_make_gx_selecteq(void*); size_t fx_size_gx_selecteq();
chdsp* fx_make_gx_graphiceq(void*); size_t fx_size_gx_graphiceq();
chdsp* fx_make_gx_tonecontroll(void*); size_t fx_size_gx_tonecontroll();
chdsp* fx_make_gx_bassboom(void*); size_t fx_size_gx_bassboom();
chdsp* fx_make_gx_bassbooster(void*); size_t fx_size_gx_bassbooster();
chdsp* fx_make_gx_bigmuff(void*); size_t fx_size_gx_bigmuff();
chdsp* fx_make_gx_mole(void*); size_t fx_size_gx_mole();
chdsp* fx_make_ex_graphic_eq(void*); size_t fx_size_ex_graphic_eq();
chdsp* fx_make_gx_hfb(void*); size_t fx_size_gx_hfb();
chdsp* fx_make_gx_hogsfoot(void*); size_t fx_size_gx_hogsfoot();
chdsp* fx_make_kpp_single2humbucker(void*); size_t fx_size_kpp_single2humbucker();
chdsp* fx_make_ex_parametric_eq(void*); size_t fx_size_ex_parametric_eq();
chdsp* fx_make_lib_speaker_sim(void*); size_t fx_size_lib_speaker_sim();
chdsp* fx_make_lib_spectral_tilt(void*); size_t fx_size_lib_spectral_tilt();
chdsp* fx_make_gx_gxtilttone(void*); size_t fx_size_gx_gxtilttone();
chdsp* fx_make_gx_tone(void*); size_t fx_size_gx_tone();
chdsp* fx_make_gx_tonestack_ampeg_rev(void*); size_t fx_size_gx_tonestack_ampeg_rev();
chdsp* fx_make_gx_tonestack_ampeg(void*); size_t fx_size_gx_tonestack_ampeg();
chdsp* fx_make_gx_tonestack_bm(void*); size_t fx_size_gx_tonestack_bm();
chdsp* fx_make_gx_tonestack_bogner(void*); size_t fx_size_gx_tonestack_bogner();
chdsp* fx_make_gx_tonestack_engl(void*); size_t fx_size_gx_tonestack_engl();
chdsp* fx_make_gx_tonestack_fender_default(void*); size_t fx_size_gx_tonestack_fender_default();
chdsp* fx_make_gx_tonestack_bassman(void*); size_t fx_size_gx_tonestack_bassman();
chdsp* fx_make_gx_tonestack_fender_blues(void*); size_t fx_size_gx_tonestack_fender_blues();
chdsp* fx_make_gx_tonestack_fender_deville(void*); size_t fx_size_gx_tonestack_fender_deville();
chdsp* fx_make_gx_tonestack_princeton(void*); size_t fx_size_gx_tonestack_princeton();
chdsp* fx_make_gx_tonestack_twin(void*); size_t fx_size_gx_tonestack_twin();
chdsp* fx_make_gx_tonestack_gibsen(void*); size_t fx_size_gx_tonestack_gibsen();
chdsp* fx_make_gx_tonestack_groove(void*); size_t fx_size_gx_tonestack_groove();
chdsp* fx_make_gx_tonestack_crunch(void*); size_t fx_size_gx_tonestack_crunch();
chdsp* fx_make_gx_tonestack_ibanez(void*); size_t fx_size_gx_tonestack_ibanez();
chdsp* fx_make_gx_tonestack_jcm2000(void*); size_t fx_size_gx_tonestack_jcm2000();
chdsp* fx_make_gx_tonestack_jcm800(void*); size_t fx_size_gx_tonestack_jcm800();
chdsp* fx_make_gx_tonestack_jtm45(void*); size_t fx_size_gx_tonestack_jtm45();
chdsp* fx_make_gx_tonestack_m2199(void*); size_t fx_size_gx_tonestack_m2199();
chdsp* fx_make_gx_tonestack_mlead(void*); size_t fx_size_gx_tonestack_mlead();
chdsp* fx_make_gx_tonestack_mesa(void*); size_t fx_size_gx_tonestack_mesa();
chdsp* fx_make_gx_tonestack_peavey(void*); size_t fx_size_gx_tonestack_peavey();
chdsp* fx_make_gx_tonestack_roland(void*); size_t fx_size_gx_tonestack_roland();
chdsp* fx_make_gx_tonestack_soldano(void*); size_t fx_size_gx_tonestack_soldano();
chdsp* fx_make_gx_tonestack_sovtek(void*); size_t fx_size_gx_tonestack_sovtek();
chdsp* fx_make_gx_tonestack_ac15(void*); size_t fx_size_gx_tonestack_ac15();
chdsp* fx_make_gx_tonestack_ac30(void*); size_t fx_size_gx_tonestack_ac30();
chdsp* fx_make_gx_highbooster(void*); size_t fx_size_gx_highbooster();
chdsp* fx_make_gx_autowah(void*); size_t fx_size_gx_autowah();
chdsp* fx_make_gx_colwah(void*); size_t fx_size_gx_colwah();
chdsp* fx_make_gx_crybaby(void*); size_t fx_size_gx_crybaby();
chdsp* fx_make_lib_autowah(void*); size_t fx_size_lib_autowah();
chdsp* fx_make_lib_crybaby(void*); size_t fx_size_lib_crybaby();
chdsp* fx_make_gx_dallaswah(void*); size_t fx_size_gx_dallaswah();
chdsp* fx_make_lib_diode_ladder(void*); size_t fx_size_lib_diode_ladder();
chdsp* fx_make_gx_gcb_95(void*); size_t fx_size_gx_gcb_95();
chdsp* fx_make_gx_dunwah(void*); size_t fx_size_gx_dunwah();
chdsp* fx_make_gx_foxwah(void*); size_t fx_size_gx_foxwah();
chdsp* fx_make_gx_jenwah(void*); size_t fx_size_gx_jenwah();
chdsp* fx_make_lib_korg35_hpf(void*); size_t fx_size_lib_korg35_hpf();
chdsp* fx_make_lib_korg35_lpf(void*); size_t fx_size_lib_korg35_lpf();
chdsp* fx_make_gx_low_high_pass(void*); size_t fx_size_gx_low_high_pass();
chdsp* fx_make_gx_maestrowah(void*); size_t fx_size_gx_maestrowah();
chdsp* fx_make_lib_moog_half_ladder(void*); size_t fx_size_lib_moog_half_ladder();
chdsp* fx_make_lib_moog_ladder(void*); size_t fx_size_lib_moog_ladder();
chdsp* fx_make_gx_moog(void*); size_t fx_size_gx_moog();
chdsp* fx_make_lib_moog_vcf(void*); size_t fx_size_lib_moog_vcf();
chdsp* fx_make_lib_oberheim_bpf(void*); size_t fx_size_lib_oberheim_bpf();
chdsp* fx_make_lib_oberheim_hpf(void*); size_t fx_size_lib_oberheim_hpf();
chdsp* fx_make_lib_oberheim_lpf(void*); size_t fx_size_lib_oberheim_lpf();
chdsp* fx_make_gx_rolandwah(void*); size_t fx_size_gx_rolandwah();
chdsp* fx_make_lib_sallenkey_lpf(void*); size_t fx_size_lib_sallenkey_lpf();
chdsp* fx_make_gx_selwah(void*); size_t fx_size_gx_selwah();
chdsp* fx_make_owl_sweep_wah(void*); size_t fx_size_owl_sweep_wah();
chdsp* fx_make_lib_tone_stack(void*); size_t fx_size_lib_tone_stack();
chdsp* fx_make_gx_voxwah(void*); size_t fx_size_gx_voxwah();
chdsp* fx_make_lib_wah4(void*); size_t fx_size_lib_wah4();
chdsp* fx_make_ex_chorus_8voice(void*); size_t fx_size_ex_chorus_8voice();
chdsp* fx_make_gx_chorus(void*); size_t fx_size_gx_chorus();
chdsp* fx_make_gx_chorus_mono(void*); size_t fx_size_gx_chorus_mono();
chdsp* fx_make_mag_constant_detune_chorus(void*); size_t fx_size_mag_constant_detune_chorus();
chdsp* fx_make_gx_flanger(void*); size_t fx_size_gx_flanger();
chdsp* fx_make_gx_flanger_gx(void*); size_t fx_size_gx_flanger_gx();
chdsp* fx_make_gx_flanger_mono(void*); size_t fx_size_gx_flanger_mono();
chdsp* fx_make_lib_flanger(void*); size_t fx_size_lib_flanger();
chdsp* fx_make_gx_mbchor(void*); size_t fx_size_gx_mbchor();
chdsp* fx_make_lib_vibrato2(void*); size_t fx_size_lib_vibrato2();
chdsp* fx_make_gx_phaser(void*); size_t fx_size_gx_phaser();
chdsp* fx_make_lib_phaser2_8(void*); size_t fx_size_lib_phaser2_8();
chdsp* fx_make_gx_phaser_mono(void*); size_t fx_size_gx_phaser_mono();
chdsp* fx_make_lib_ring_mod(void*); size_t fx_size_lib_ring_mod();
chdsp* fx_make_tdg_rotary_speakers(void*); size_t fx_size_tdg_rotary_speakers();
chdsp* fx_make_ex_tremolo_autopan(void*); size_t fx_size_ex_tremolo_autopan();
chdsp* fx_make_gx_switched_tremolo(void*); size_t fx_size_gx_switched_tremolo();
chdsp* fx_make_tdg_tri_chorus(void*); size_t fx_size_tdg_tri_chorus();
chdsp* fx_make_gx_gxtubetremelo(void*); size_t fx_size_gx_gxtubetremelo();
chdsp* fx_make_gx_gxtubevibrato(void*); size_t fx_size_gx_gxtubevibrato();
chdsp* fx_make_gx_tremolo(void*); size_t fx_size_gx_tremolo();
chdsp* fx_make_ex_harmonic_exciter(void*); size_t fx_size_ex_harmonic_exciter();
chdsp* fx_make_lib_harmonizer(void*); size_t fx_size_lib_harmonizer();
chdsp* fx_make_kpp_octaver(void*); size_t fx_size_kpp_octaver();
chdsp* fx_make_tdg_parametric_pitch_shifter(void*); size_t fx_size_tdg_parametric_pitch_shifter();
chdsp* fx_make_lib_pitch_shift(void*); size_t fx_size_lib_pitch_shift();
chdsp* fx_make_lib_tape_stop(void*); size_t fx_size_lib_tape_stop();
chdsp* fx_make_luca_chamberlin(void*); size_t fx_size_luca_chamberlin();
chdsp* fx_make_lib_dattorro(void*); size_t fx_size_lib_dattorro();
chdsp* fx_make_tdg_duck_reverb(void*); size_t fx_size_tdg_duck_reverb();
chdsp* fx_make_owl_faustverb(void*); size_t fx_size_owl_faustverb();
chdsp* fx_make_lib_fdn_reverb(void*); size_t fx_size_lib_fdn_reverb();
chdsp* fx_make_gx_freeverb(void*); size_t fx_size_gx_freeverb();
chdsp* fx_make_lib_freeverb(void*); size_t fx_size_lib_freeverb();
chdsp* fx_make_luca_greisinger_480l(void*); size_t fx_size_luca_greisinger_480l();
chdsp* fx_make_lib_greyhole(void*); size_t fx_size_lib_greyhole();
chdsp* fx_make_lib_jcrev(void*); size_t fx_size_lib_jcrev();
chdsp* fx_make_lib_jpverb(void*); size_t fx_size_lib_jpverb();
chdsp* fx_make_luca_moorer(void*); size_t fx_size_luca_moorer();
chdsp* fx_make_gx_mbreverb(void*); size_t fx_size_gx_mbreverb();
chdsp* fx_make_tdg_freeverb3(void*); size_t fx_size_tdg_freeverb3();
chdsp* fx_make_tdg_room_simulator(void*); size_t fx_size_tdg_room_simulator();
chdsp* fx_make_tdg_shimmer(void*); size_t fx_size_tdg_shimmer();
chdsp* fx_make_tdg_shimmizita(void*); size_t fx_size_tdg_shimmizita();
chdsp* fx_make_lib_kb_rom_rev1(void*); size_t fx_size_lib_kb_rom_rev1();
chdsp* fx_make_lib_springreverb(void*); size_t fx_size_lib_springreverb();
chdsp* fx_make_gx_stereoverb(void*); size_t fx_size_gx_stereoverb();
chdsp* fx_make_lib_vital_rev(void*); size_t fx_size_lib_vital_rev();
chdsp* fx_make_gx_zita_rev1(void*); size_t fx_size_gx_zita_rev1();
chdsp* fx_make_lib_zita_rev1(void*); size_t fx_size_lib_zita_rev1();
chdsp* fx_make_tdg_zita_spread(void*); size_t fx_size_tdg_zita_spread();
chdsp* fx_make_gx_gxechocat(void*); size_t fx_size_gx_gxechocat();
chdsp* fx_make_gx_delay(void*); size_t fx_size_gx_delay();
chdsp* fx_make_tdg_delay_colored(void*); size_t fx_size_tdg_delay_colored();
chdsp* fx_make_tdg_delay_detune(void*); size_t fx_size_tdg_delay_detune();
chdsp* fx_make_tdg_delay_duck(void*); size_t fx_size_tdg_delay_duck();
chdsp* fx_make_tdg_delay_emu(void*); size_t fx_size_tdg_delay_emu();
chdsp* fx_make_tdg_delay_flange(void*); size_t fx_size_tdg_delay_flange();
chdsp* fx_make_tdg_delay_ps(void*); size_t fx_size_tdg_delay_ps();
chdsp* fx_make_tdg_delay_ringmod(void*); size_t fx_size_tdg_delay_ringmod();
chdsp* fx_make_tdg_delay_wah(void*); size_t fx_size_tdg_delay_wah();
chdsp* fx_make_gx_duck_delay(void*); size_t fx_size_gx_duck_delay();
chdsp* fx_make_gx_echo(void*); size_t fx_size_gx_echo();
chdsp* fx_make_gx_mbdel(void*); size_t fx_size_gx_mbdel();
chdsp* fx_make_gx_mbe(void*); size_t fx_size_gx_mbe();
chdsp* fx_make_tdg_multi_tap_echo(void*); size_t fx_size_tdg_multi_tap_echo();
chdsp* fx_make_ex_pitch_feedback_delay(void*); size_t fx_size_ex_pitch_feedback_delay();
chdsp* fx_make_lib_reverse_echo(void*); size_t fx_size_lib_reverse_echo();
chdsp* fx_make_lib_echo(void*); size_t fx_size_lib_echo();
chdsp* fx_make_owl_smooth_delay(void*); size_t fx_size_owl_smooth_delay();
chdsp* fx_make_gx_stereodelay(void*); size_t fx_size_gx_stereodelay();
chdsp* fx_make_gx_stereoecho(void*); size_t fx_size_gx_stereoecho();
chdsp* fx_make_gx_gxtubedelay(void*); size_t fx_size_gx_gxtubedelay();

struct EffectEntry { const char* id; chdsp* (*make)(void*); size_t (*size)(); };
enum { NUM_EFFECTS = 269 };
static const EffectEntry EFFECTS[NUM_EFFECTS] = {
    { "tape-delay", fx_make_tape_delay, fx_size_tape_delay },
    { "dattorro-plate", fx_make_dattorro_plate, fx_size_dattorro_plate },
    { "bbd-chorus", fx_make_bbd_chorus, fx_size_bbd_chorus },
    { "harmonic-tremolo", fx_make_harmonic_tremolo, fx_size_harmonic_tremolo },
    { "dynamic-overdrive", fx_make_dynamic_overdrive, fx_size_dynamic_overdrive },
    { "klon-centaur", fx_make_klon_centaur, fx_size_klon_centaur },
    { "infinite-compressor", fx_make_infinite_compressor, fx_size_infinite_compressor },
    { "multi-phaser", fx_make_multi_phaser, fx_size_multi_phaser },
    { "silicon-fuzz", fx_make_silicon_fuzz, fx_size_silicon_fuzz },
    { "auto-wah", fx_make_auto_wah, fx_size_auto_wah },
    { "pitch-octaver", fx_make_pitch_octaver, fx_size_pitch_octaver },
    { "analog-flanger", fx_make_analog_flanger, fx_size_analog_flanger },
    { "spring-reverb", fx_make_spring_reverb, fx_size_spring_reverb },
    { "clean-boost", fx_make_clean_boost, fx_size_clean_boost },
    { "reverse-delay", fx_make_reverse_delay, fx_size_reverse_delay },
    { "lofi-bitcrush", fx_make_lofi_bitcrush, fx_size_lofi_bitcrush },
    { "drum-pumping-comp", fx_make_drum_pumping_comp, fx_size_drum_pumping_comp },
    { "gated-snare-reverb", fx_make_gated_snare_reverb, fx_size_gated_snare_reverb },
    { "resonant-dj-filter", fx_make_resonant_dj_filter, fx_size_resonant_dj_filter },
    { "tape-saturation-drum", fx_make_tape_saturation_drum, fx_size_tape_saturation_drum },
    { "beat-repeater", fx_make_beat_repeater, fx_size_beat_repeater },
    { "sub-resonator", fx_make_sub_resonator, fx_size_sub_resonator },
    { "drum-slammer", fx_make_drum_slammer, fx_size_drum_slammer },
    { "ring-mod-percussion", fx_make_ring_mod_percussion, fx_size_ring_mod_percussion },
    { "transient-shaper", fx_make_transient_shaper, fx_size_transient_shaper },
    { "stereo-pingpong-beat", fx_make_stereo_pingpong_beat, fx_size_stereo_pingpong_beat },
    { "wavefolder-dirt", fx_make_wavefolder_dirt, fx_size_wavefolder_dirt },
    { "comb-resonator", fx_make_comb_resonator, fx_size_comb_resonator },
    { "freq-shifter", fx_make_freq_shifter, fx_size_freq_shifter },
    { "bbd-drum-delay", fx_make_bbd_drum_delay, fx_size_bbd_drum_delay },
    { "expander-gate", fx_make_expander_gate, fx_size_expander_gate },
    { "lib-12ax7-preamp", fx_make_lib_12ax7_preamp, fx_size_lib_12ax7_preamp },
    { "gx-gx-studiopre", fx_make_gx_gx_studiopre, fx_size_gx_gx_studiopre },
    { "gx-gxamp15", fx_make_gx_gxamp15, fx_size_gx_gxamp15 },
    { "gx-gxamp16", fx_make_gx_gxamp16, fx_size_gx_gxamp16 },
    { "gx-gxamp14", fx_make_gx_gxamp14, fx_size_gx_gxamp14 },
    { "gx-gxamp17", fx_make_gx_gxamp17, fx_size_gx_gxamp17 },
    { "gx-gxamp4", fx_make_gx_gxamp4, fx_size_gx_gxamp4 },
    { "gx-gxamp8", fx_make_gx_gxamp8, fx_size_gx_gxamp8 },
    { "gx-gxamp3", fx_make_gx_gxamp3, fx_size_gx_gxamp3 },
    { "gx-gxamp11", fx_make_gx_gxamp11, fx_size_gx_gxamp11 },
    { "gx-gxamp5", fx_make_gx_gxamp5, fx_size_gx_gxamp5 },
    { "gx-gxamp7", fx_make_gx_gxamp7, fx_size_gx_gxamp7 },
    { "gx-gxamp", fx_make_gx_gxamp, fx_size_gx_gxamp },
    { "gx-gxamp9", fx_make_gx_gxamp9, fx_size_gx_gxamp9 },
    { "gx-gxamp18", fx_make_gx_gxamp18, fx_size_gx_gxamp18 },
    { "gx-gxamp12", fx_make_gx_gxamp12, fx_size_gx_gxamp12 },
    { "gx-gxamp6", fx_make_gx_gxamp6, fx_size_gx_gxamp6 },
    { "gx-gxamp10", fx_make_gx_gxamp10, fx_size_gx_gxamp10 },
    { "gx-gxamp13", fx_make_gx_gxamp13, fx_size_gx_gxamp13 },
    { "gx-gxamp2", fx_make_gx_gxamp2, fx_size_gx_gxamp2 },
    { "gx-tube", fx_make_gx_tube, fx_size_gx_tube },
    { "ex-guitarix-amp", fx_make_ex_guitarix_amp, fx_size_ex_guitarix_amp },
    { "kpp-tubeamp", fx_make_kpp_tubeamp, fx_size_kpp_tubeamp },
    { "gx-gxmetal-amp", fx_make_gx_gxmetal_amp, fx_size_gx_gxmetal_amp },
    { "gx-gxmetal-head", fx_make_gx_gxmetal_head, fx_size_gx_gxmetal_head },
    { "gx-preamp", fx_make_gx_preamp, fx_size_gx_preamp },
    { "gx-gx-bigchump", fx_make_gx_gx_bigchump, fx_size_gx_gx_bigchump },
    { "gx-gx-chump", fx_make_gx_gx_chump, fx_size_gx_gx_chump },
    { "gx-gx-vibrochump", fx_make_gx_gx_vibrochump, fx_size_gx_gx_vibrochump },
    { "gx-reso-tube", fx_make_gx_reso_tube, fx_size_gx_reso_tube },
    { "gx-tube3", fx_make_gx_tube3, fx_size_gx_tube3 },
    { "gx-valve", fx_make_gx_valve, fx_size_gx_valve },
    { "gx-gx-w20", fx_make_gx_gx_w20, fx_size_gx_gx_w20 },
    { "lib-adaa-drive", fx_make_lib_adaa_drive, fx_size_lib_adaa_drive },
    { "gx-astrofuzz", fx_make_gx_astrofuzz, fx_size_gx_astrofuzz },
    { "gx-axface", fx_make_gx_axface, fx_size_gx_axface },
    { "barabas-tubescreamer", fx_make_barabas_tubescreamer, fx_size_barabas_tubescreamer },
    { "gx-bfuzz", fx_make_gx_bfuzz, fx_size_gx_bfuzz },
    { "gx-bmp", fx_make_gx_bmp, fx_size_gx_bmp },
    { "gx-bossds1", fx_make_gx_bossds1, fx_size_gx_bossds1 },
    { "gx-buzz", fx_make_gx_buzz, fx_size_gx_buzz },
    { "gx-coverd", fx_make_gx_coverd, fx_size_gx_coverd },
    { "gx-cstb", fx_make_gx_cstb, fx_size_gx_cstb },
    { "lib-cubicnl", fx_make_lib_cubicnl, fx_size_lib_cubicnl },
    { "gx-rangem", fx_make_gx_rangem, fx_size_gx_rangem },
    { "gx-ruin", fx_make_gx_ruin, fx_size_gx_ruin },
    { "gx-eldist", fx_make_gx_eldist, fx_size_gx_eldist },
    { "gx-ffreak", fx_make_gx_ffreak, fx_size_gx_ffreak },
    { "gx-foxeylady", fx_make_gx_foxeylady, fx_size_gx_foxeylady },
    { "gx-fuzzfacefm", fx_make_gx_fuzzfacefm, fx_size_gx_fuzzfacefm },
    { "gx-fuzzface", fx_make_gx_fuzzface, fx_size_gx_fuzzface },
    { "gx-fuzzfacerm", fx_make_gx_fuzzfacerm, fx_size_gx_fuzzfacerm },
    { "gx-drive", fx_make_gx_drive, fx_size_gx_drive },
    { "gx-hornet", fx_make_gx_hornet, fx_size_gx_hornet },
    { "gx-ts9sim", fx_make_gx_ts9sim, fx_size_gx_ts9sim },
    { "kpp-bluedream", fx_make_kpp_bluedream, fx_size_kpp_bluedream },
    { "kpp-distruction", fx_make_kpp_distruction, fx_size_kpp_distruction },
    { "kpp-fuzz", fx_make_kpp_fuzz, fx_size_kpp_fuzz },
    { "gx-lpbboost", fx_make_gx_lpbboost, fx_size_gx_lpbboost },
    { "gx-muff", fx_make_gx_muff, fx_size_gx_muff },
    { "gx-mbclipper", fx_make_gx_mbclipper, fx_size_gx_mbclipper },
    { "gx-mbd", fx_make_gx_mbd, fx_size_gx_mbd },
    { "gx-gx-distortion", fx_make_gx_gx_distortion, fx_size_gx_gx_distortion },
    { "gx-mxrdist", fx_make_gx_mxrdist, fx_size_gx_mxrdist },
    { "gx-overdrive", fx_make_gx_overdrive, fx_size_gx_overdrive },
    { "gx-aclipper", fx_make_gx_aclipper, fx_size_gx_aclipper },
    { "gx-scream", fx_make_gx_scream, fx_size_gx_scream },
    { "gx-softclip", fx_make_gx_softclip, fx_size_gx_softclip },
    { "lib-tape-hysteresis", fx_make_lib_tape_hysteresis, fx_size_lib_tape_hysteresis },
    { "gx-buffb", fx_make_gx_buffb, fx_size_gx_buffb },
    { "gx-fumaster", fx_make_gx_fumaster, fx_size_gx_fumaster },
    { "lib-wavefolder", fx_make_lib_wavefolder, fx_size_lib_wavefolder },
    { "lib-1176", fx_make_lib_1176, fx_size_lib_1176 },
    { "lib-3band-compressor", fx_make_lib_3band_compressor, fx_size_lib_3band_compressor },
    { "mag-character-compressor", fx_make_mag_character_compressor, fx_size_mag_character_compressor },
    { "gx-compressor", fx_make_gx_compressor, fx_size_gx_compressor },
    { "gx-expander", fx_make_gx_expander, fx_size_gx_expander },
    { "lib-expander", fx_make_lib_expander, fx_size_lib_expander },
    { "lib-fb-compressor", fx_make_lib_fb_compressor, fx_size_lib_fb_compressor },
    { "lib-ff-compressor", fx_make_lib_ff_compressor, fx_size_lib_ff_compressor },
    { "ex-granular-gate", fx_make_ex_granular_gate, fx_size_ex_granular_gate },
    { "lib-jos-compressor", fx_make_lib_jos_compressor, fx_size_lib_jos_compressor },
    { "kpp-deadgate", fx_make_kpp_deadgate, fx_size_kpp_deadgate },
    { "lib-lookahead-limiter", fx_make_lib_lookahead_limiter, fx_size_lib_lookahead_limiter },
    { "gx-mbc", fx_make_gx_mbc, fx_size_gx_mbc },
    { "gx-mbcs", fx_make_gx_mbcs, fx_size_gx_mbcs },
    { "lib-gate", fx_make_lib_gate, fx_size_lib_gate },
    { "owl-qompander", fx_make_owl_qompander, fx_size_owl_qompander },
    { "lib-rms-peak-limiter", fx_make_lib_rms_peak_limiter, fx_size_lib_rms_peak_limiter },
    { "lib-rms-compressor", fx_make_lib_rms_compressor, fx_size_lib_rms_compressor },
    { "gx-susta", fx_make_gx_susta, fx_size_gx_susta },
    { "gx-eq", fx_make_gx_eq, fx_size_gx_eq },
    { "gx-selecteq", fx_make_gx_selecteq, fx_size_gx_selecteq },
    { "gx-graphiceq", fx_make_gx_graphiceq, fx_size_gx_graphiceq },
    { "gx-tonecontroll", fx_make_gx_tonecontroll, fx_size_gx_tonecontroll },
    { "gx-bassboom", fx_make_gx_bassboom, fx_size_gx_bassboom },
    { "gx-bassbooster", fx_make_gx_bassbooster, fx_size_gx_bassbooster },
    { "gx-bigmuff", fx_make_gx_bigmuff, fx_size_gx_bigmuff },
    { "gx-mole", fx_make_gx_mole, fx_size_gx_mole },
    { "ex-graphic-eq", fx_make_ex_graphic_eq, fx_size_ex_graphic_eq },
    { "gx-hfb", fx_make_gx_hfb, fx_size_gx_hfb },
    { "gx-hogsfoot", fx_make_gx_hogsfoot, fx_size_gx_hogsfoot },
    { "kpp-single2humbucker", fx_make_kpp_single2humbucker, fx_size_kpp_single2humbucker },
    { "ex-parametric-eq", fx_make_ex_parametric_eq, fx_size_ex_parametric_eq },
    { "lib-speaker-sim", fx_make_lib_speaker_sim, fx_size_lib_speaker_sim },
    { "lib-spectral-tilt", fx_make_lib_spectral_tilt, fx_size_lib_spectral_tilt },
    { "gx-gxtilttone", fx_make_gx_gxtilttone, fx_size_gx_gxtilttone },
    { "gx-tone", fx_make_gx_tone, fx_size_gx_tone },
    { "gx-tonestack-ampeg-rev", fx_make_gx_tonestack_ampeg_rev, fx_size_gx_tonestack_ampeg_rev },
    { "gx-tonestack-ampeg", fx_make_gx_tonestack_ampeg, fx_size_gx_tonestack_ampeg },
    { "gx-tonestack-bm", fx_make_gx_tonestack_bm, fx_size_gx_tonestack_bm },
    { "gx-tonestack-bogner", fx_make_gx_tonestack_bogner, fx_size_gx_tonestack_bogner },
    { "gx-tonestack-engl", fx_make_gx_tonestack_engl, fx_size_gx_tonestack_engl },
    { "gx-tonestack-fender-default", fx_make_gx_tonestack_fender_default, fx_size_gx_tonestack_fender_default },
    { "gx-tonestack-bassman", fx_make_gx_tonestack_bassman, fx_size_gx_tonestack_bassman },
    { "gx-tonestack-fender-blues", fx_make_gx_tonestack_fender_blues, fx_size_gx_tonestack_fender_blues },
    { "gx-tonestack-fender-deville", fx_make_gx_tonestack_fender_deville, fx_size_gx_tonestack_fender_deville },
    { "gx-tonestack-princeton", fx_make_gx_tonestack_princeton, fx_size_gx_tonestack_princeton },
    { "gx-tonestack-twin", fx_make_gx_tonestack_twin, fx_size_gx_tonestack_twin },
    { "gx-tonestack-gibsen", fx_make_gx_tonestack_gibsen, fx_size_gx_tonestack_gibsen },
    { "gx-tonestack-groove", fx_make_gx_tonestack_groove, fx_size_gx_tonestack_groove },
    { "gx-tonestack-crunch", fx_make_gx_tonestack_crunch, fx_size_gx_tonestack_crunch },
    { "gx-tonestack-ibanez", fx_make_gx_tonestack_ibanez, fx_size_gx_tonestack_ibanez },
    { "gx-tonestack-jcm2000", fx_make_gx_tonestack_jcm2000, fx_size_gx_tonestack_jcm2000 },
    { "gx-tonestack-jcm800", fx_make_gx_tonestack_jcm800, fx_size_gx_tonestack_jcm800 },
    { "gx-tonestack-jtm45", fx_make_gx_tonestack_jtm45, fx_size_gx_tonestack_jtm45 },
    { "gx-tonestack-m2199", fx_make_gx_tonestack_m2199, fx_size_gx_tonestack_m2199 },
    { "gx-tonestack-mlead", fx_make_gx_tonestack_mlead, fx_size_gx_tonestack_mlead },
    { "gx-tonestack-mesa", fx_make_gx_tonestack_mesa, fx_size_gx_tonestack_mesa },
    { "gx-tonestack-peavey", fx_make_gx_tonestack_peavey, fx_size_gx_tonestack_peavey },
    { "gx-tonestack-roland", fx_make_gx_tonestack_roland, fx_size_gx_tonestack_roland },
    { "gx-tonestack-soldano", fx_make_gx_tonestack_soldano, fx_size_gx_tonestack_soldano },
    { "gx-tonestack-sovtek", fx_make_gx_tonestack_sovtek, fx_size_gx_tonestack_sovtek },
    { "gx-tonestack-ac15", fx_make_gx_tonestack_ac15, fx_size_gx_tonestack_ac15 },
    { "gx-tonestack-ac30", fx_make_gx_tonestack_ac30, fx_size_gx_tonestack_ac30 },
    { "gx-highbooster", fx_make_gx_highbooster, fx_size_gx_highbooster },
    { "gx-autowah", fx_make_gx_autowah, fx_size_gx_autowah },
    { "gx-colwah", fx_make_gx_colwah, fx_size_gx_colwah },
    { "gx-crybaby", fx_make_gx_crybaby, fx_size_gx_crybaby },
    { "lib-autowah", fx_make_lib_autowah, fx_size_lib_autowah },
    { "lib-crybaby", fx_make_lib_crybaby, fx_size_lib_crybaby },
    { "gx-dallaswah", fx_make_gx_dallaswah, fx_size_gx_dallaswah },
    { "lib-diode-ladder", fx_make_lib_diode_ladder, fx_size_lib_diode_ladder },
    { "gx-gcb-95", fx_make_gx_gcb_95, fx_size_gx_gcb_95 },
    { "gx-dunwah", fx_make_gx_dunwah, fx_size_gx_dunwah },
    { "gx-foxwah", fx_make_gx_foxwah, fx_size_gx_foxwah },
    { "gx-jenwah", fx_make_gx_jenwah, fx_size_gx_jenwah },
    { "lib-korg35-hpf", fx_make_lib_korg35_hpf, fx_size_lib_korg35_hpf },
    { "lib-korg35-lpf", fx_make_lib_korg35_lpf, fx_size_lib_korg35_lpf },
    { "gx-low-high-pass", fx_make_gx_low_high_pass, fx_size_gx_low_high_pass },
    { "gx-maestrowah", fx_make_gx_maestrowah, fx_size_gx_maestrowah },
    { "lib-moog-half-ladder", fx_make_lib_moog_half_ladder, fx_size_lib_moog_half_ladder },
    { "lib-moog-ladder", fx_make_lib_moog_ladder, fx_size_lib_moog_ladder },
    { "gx-moog", fx_make_gx_moog, fx_size_gx_moog },
    { "lib-moog-vcf", fx_make_lib_moog_vcf, fx_size_lib_moog_vcf },
    { "lib-oberheim-bpf", fx_make_lib_oberheim_bpf, fx_size_lib_oberheim_bpf },
    { "lib-oberheim-hpf", fx_make_lib_oberheim_hpf, fx_size_lib_oberheim_hpf },
    { "lib-oberheim-lpf", fx_make_lib_oberheim_lpf, fx_size_lib_oberheim_lpf },
    { "gx-rolandwah", fx_make_gx_rolandwah, fx_size_gx_rolandwah },
    { "lib-sallenkey-lpf", fx_make_lib_sallenkey_lpf, fx_size_lib_sallenkey_lpf },
    { "gx-selwah", fx_make_gx_selwah, fx_size_gx_selwah },
    { "owl-sweep-wah", fx_make_owl_sweep_wah, fx_size_owl_sweep_wah },
    { "lib-tone-stack", fx_make_lib_tone_stack, fx_size_lib_tone_stack },
    { "gx-voxwah", fx_make_gx_voxwah, fx_size_gx_voxwah },
    { "lib-wah4", fx_make_lib_wah4, fx_size_lib_wah4 },
    { "ex-chorus-8voice", fx_make_ex_chorus_8voice, fx_size_ex_chorus_8voice },
    { "gx-chorus", fx_make_gx_chorus, fx_size_gx_chorus },
    { "gx-chorus-mono", fx_make_gx_chorus_mono, fx_size_gx_chorus_mono },
    { "mag-constant-detune-chorus", fx_make_mag_constant_detune_chorus, fx_size_mag_constant_detune_chorus },
    { "gx-flanger", fx_make_gx_flanger, fx_size_gx_flanger },
    { "gx-flanger-gx", fx_make_gx_flanger_gx, fx_size_gx_flanger_gx },
    { "gx-flanger-mono", fx_make_gx_flanger_mono, fx_size_gx_flanger_mono },
    { "lib-flanger", fx_make_lib_flanger, fx_size_lib_flanger },
    { "gx-mbchor", fx_make_gx_mbchor, fx_size_gx_mbchor },
    { "lib-vibrato2", fx_make_lib_vibrato2, fx_size_lib_vibrato2 },
    { "gx-phaser", fx_make_gx_phaser, fx_size_gx_phaser },
    { "lib-phaser2-8", fx_make_lib_phaser2_8, fx_size_lib_phaser2_8 },
    { "gx-phaser-mono", fx_make_gx_phaser_mono, fx_size_gx_phaser_mono },
    { "lib-ring-mod", fx_make_lib_ring_mod, fx_size_lib_ring_mod },
    { "tdg-rotary-speakers", fx_make_tdg_rotary_speakers, fx_size_tdg_rotary_speakers },
    { "ex-tremolo-autopan", fx_make_ex_tremolo_autopan, fx_size_ex_tremolo_autopan },
    { "gx-switched-tremolo", fx_make_gx_switched_tremolo, fx_size_gx_switched_tremolo },
    { "tdg-tri-chorus", fx_make_tdg_tri_chorus, fx_size_tdg_tri_chorus },
    { "gx-gxtubetremelo", fx_make_gx_gxtubetremelo, fx_size_gx_gxtubetremelo },
    { "gx-gxtubevibrato", fx_make_gx_gxtubevibrato, fx_size_gx_gxtubevibrato },
    { "gx-tremolo", fx_make_gx_tremolo, fx_size_gx_tremolo },
    { "ex-harmonic-exciter", fx_make_ex_harmonic_exciter, fx_size_ex_harmonic_exciter },
    { "lib-harmonizer", fx_make_lib_harmonizer, fx_size_lib_harmonizer },
    { "kpp-octaver", fx_make_kpp_octaver, fx_size_kpp_octaver },
    { "tdg-parametric-pitch-shifter", fx_make_tdg_parametric_pitch_shifter, fx_size_tdg_parametric_pitch_shifter },
    { "lib-pitch-shift", fx_make_lib_pitch_shift, fx_size_lib_pitch_shift },
    { "lib-tape-stop", fx_make_lib_tape_stop, fx_size_lib_tape_stop },
    { "luca-chamberlin", fx_make_luca_chamberlin, fx_size_luca_chamberlin },
    { "lib-dattorro", fx_make_lib_dattorro, fx_size_lib_dattorro },
    { "tdg-duck-reverb", fx_make_tdg_duck_reverb, fx_size_tdg_duck_reverb },
    { "owl-faustverb", fx_make_owl_faustverb, fx_size_owl_faustverb },
    { "lib-fdn-reverb", fx_make_lib_fdn_reverb, fx_size_lib_fdn_reverb },
    { "gx-freeverb", fx_make_gx_freeverb, fx_size_gx_freeverb },
    { "lib-freeverb", fx_make_lib_freeverb, fx_size_lib_freeverb },
    { "luca-greisinger-480l", fx_make_luca_greisinger_480l, fx_size_luca_greisinger_480l },
    { "lib-greyhole", fx_make_lib_greyhole, fx_size_lib_greyhole },
    { "lib-jcrev", fx_make_lib_jcrev, fx_size_lib_jcrev },
    { "lib-jpverb", fx_make_lib_jpverb, fx_size_lib_jpverb },
    { "luca-moorer", fx_make_luca_moorer, fx_size_luca_moorer },
    { "gx-mbreverb", fx_make_gx_mbreverb, fx_size_gx_mbreverb },
    { "tdg-freeverb3", fx_make_tdg_freeverb3, fx_size_tdg_freeverb3 },
    { "tdg-room-simulator", fx_make_tdg_room_simulator, fx_size_tdg_room_simulator },
    { "tdg-shimmer", fx_make_tdg_shimmer, fx_size_tdg_shimmer },
    { "tdg-shimmizita", fx_make_tdg_shimmizita, fx_size_tdg_shimmizita },
    { "lib-kb-rom-rev1", fx_make_lib_kb_rom_rev1, fx_size_lib_kb_rom_rev1 },
    { "lib-springreverb", fx_make_lib_springreverb, fx_size_lib_springreverb },
    { "gx-stereoverb", fx_make_gx_stereoverb, fx_size_gx_stereoverb },
    { "lib-vital-rev", fx_make_lib_vital_rev, fx_size_lib_vital_rev },
    { "gx-zita-rev1", fx_make_gx_zita_rev1, fx_size_gx_zita_rev1 },
    { "lib-zita-rev1", fx_make_lib_zita_rev1, fx_size_lib_zita_rev1 },
    { "tdg-zita-spread", fx_make_tdg_zita_spread, fx_size_tdg_zita_spread },
    { "gx-gxechocat", fx_make_gx_gxechocat, fx_size_gx_gxechocat },
    { "gx-delay", fx_make_gx_delay, fx_size_gx_delay },
    { "tdg-delay-colored", fx_make_tdg_delay_colored, fx_size_tdg_delay_colored },
    { "tdg-delay-detune", fx_make_tdg_delay_detune, fx_size_tdg_delay_detune },
    { "tdg-delay-duck", fx_make_tdg_delay_duck, fx_size_tdg_delay_duck },
    { "tdg-delay-emu", fx_make_tdg_delay_emu, fx_size_tdg_delay_emu },
    { "tdg-delay-flange", fx_make_tdg_delay_flange, fx_size_tdg_delay_flange },
    { "tdg-delay-ps", fx_make_tdg_delay_ps, fx_size_tdg_delay_ps },
    { "tdg-delay-ringmod", fx_make_tdg_delay_ringmod, fx_size_tdg_delay_ringmod },
    { "tdg-delay-wah", fx_make_tdg_delay_wah, fx_size_tdg_delay_wah },
    { "gx-duck-delay", fx_make_gx_duck_delay, fx_size_gx_duck_delay },
    { "gx-echo", fx_make_gx_echo, fx_size_gx_echo },
    { "gx-mbdel", fx_make_gx_mbdel, fx_size_gx_mbdel },
    { "gx-mbe", fx_make_gx_mbe, fx_size_gx_mbe },
    { "tdg-multi-tap-echo", fx_make_tdg_multi_tap_echo, fx_size_tdg_multi_tap_echo },
    { "ex-pitch-feedback-delay", fx_make_ex_pitch_feedback_delay, fx_size_ex_pitch_feedback_delay },
    { "lib-reverse-echo", fx_make_lib_reverse_echo, fx_size_lib_reverse_echo },
    { "lib-echo", fx_make_lib_echo, fx_size_lib_echo },
    { "owl-smooth-delay", fx_make_owl_smooth_delay, fx_size_owl_smooth_delay },
    { "gx-stereodelay", fx_make_gx_stereodelay, fx_size_gx_stereodelay },
    { "gx-stereoecho", fx_make_gx_stereoecho, fx_size_gx_stereoecho },
    { "gx-gxtubedelay", fx_make_gx_gxtubedelay, fx_size_gx_gxtubedelay },
};
