// GENERATED by tools/build-firmware.mjs — do not edit. Source: built-in default set
#pragma once
#include "faust/dynamic-overdrive.h"
#include "faust/clean-boost.h"
#include "faust/tape-delay.h"

#define CH_EFFECTS(X) \
    X(DynamicOverdrive, "dynamic-overdrive") \
    X(CleanBoost, "clean-boost") \
    X(TapeDelay, "tape-delay")

enum { NUM_PATCHES = 4, MAX_STAGES = 7, MAX_VALUES = 24 };
struct ValueDef { const char* path; float value; };
struct StageDef { int effect; bool on; int nvalues; ValueDef values[MAX_VALUES]; };
struct PotDef   { int stage; const char* path; };
struct PatchDef { const char* name; bool potsLocked; int hue; int nstages; StageDef stages[MAX_STAGES]; PotDef pots[3]; };

static const PatchDef PATCHES[NUM_PATCHES] = {
    // Patch A: Dynamic Overdrive
    { "A", false, 13, 1,
      { 
      { 0, true, 3, { { "/DynamicOverdrive/Gain", 18.0f }, { "/DynamicOverdrive/Tone", 2800.0f }, { "/DynamicOverdrive/Level", 0.6f } } }
      },
      { { 0, "/DynamicOverdrive/Gain" }, { 0, "/DynamicOverdrive/Tone" }, { 0, "/DynamicOverdrive/Level" } } },
    // Patch B: Dynamic Overdrive
    { "B", false, 13, 1,
      { 
      { 0, true, 3, { { "/DynamicOverdrive/Gain", 36.0f }, { "/DynamicOverdrive/Tone", 1800.0f }, { "/DynamicOverdrive/Level", 0.5f } } }
      },
      { { 0, "/DynamicOverdrive/Gain" }, { 0, "/DynamicOverdrive/Tone" }, { 0, "/DynamicOverdrive/Level" } } },
    // Patch C: JFET Preamp Boost
    { "C", false, 16, 1,
      { 
      { 1, true, 3, { { "/JFETBoost/Boost", 12.0f }, { "/JFETBoost/Tilt_EQ", 2.0f }, { "/JFETBoost/Master", 0.8f } } }
      },
      { { 0, "/JFETBoost/Boost" }, { 0, "/JFETBoost/Tilt_EQ" }, { 0, "/JFETBoost/Master" } } },
    // Patch D: Tape Delay
    { "D", false, 179, 1,
      { 
      { 2, true, 3, { { "/TapeDelay/Time", 420.0f }, { "/TapeDelay/Feedback", 0.5f }, { "/TapeDelay/Mix", 0.45f } } }
      },
      { { 0, "/TapeDelay/Time" }, { 0, "/TapeDelay/Feedback" }, { 0, "/TapeDelay/Mix" } } },
};
